#                                                               ██████   ██████   ██████ ██   ██ ███████ ██████
#   ███████  ██████  ████    ██████       ██████  ████   ██     ██   ██ ██    ██ ██      ██  ██  ██      ██   ██
#      ███  ██    ██ ██  ██ ██           ██    ██ ██ ██  ██     ██   ██ ██    ██ ██      █████   █████   ██████
#    ███    ██    ██ ██     ██   ███     ██    ██ ██  ██ ██     ██   ██ ██    ██ ██      ██  ██  ██      ██   ██
#   ███████  ██████  ██      ██████       ██████  ██   ████     ██████   ██████   ██████ ██   ██ ███████ ██   ██
# Portable, Server independent, Docker-based code to get the zorg Websites and Services up, running, and hosted.
# Copyright (C) 2024  zorg Verein <https://github.com/zorgch>
#
#   This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
#
#   This program comes with ABSOLUTELY NO WARRANTY; for details read the README.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see the LICENSE.

#============================
# --==[ DOCKER SERVICES ]==--
#============================
services:
    #----------------------------
    # 🔐 Self-signed certificates
    #----------------------------
    sslcerts:
        profiles: [ "setup" ]
        image: alpine/mkcert
        platform: ${OS_PLATFORM:-linux/amd64}
        container_name: ${COMPOSE_PROJECT_NAME:+${COMPOSE_PROJECT_NAME}-}sslcerts
        restart: "no"
        security_opt:
            - "no-new-privileges:true"
        cap_drop:
            - ALL
        network_mode: "none"
        entrypoint: sh
        command: >
            -c 'mkcert -install &&
            mkcert -cert-file /certs/fullchain.cert -key-file /certs/privkey.key ${DOMAINNAME} *.${DOMAINNAME} ${SECONDARY_DOMAINNAME:+${SECONDARY_DOMAINNAME} *.${SECONDARY_DOMAINNAME}} ${SELFSIGNED_CERT_HOSTS} &&
            cat /root/.local/share/mkcert/rootCA.pem >> /certs/fullchain.cert &&
            chmod 644 /certs/fullchain.cert && chmod 644 /certs/privkey.key'
        volumes:
            - sslcerts-files:/certs:rw # :rw = read+write (explicit)

    #--------------------------------
    # 🚨 Docker Service Notifications
    #--------------------------------
    servicealerts:
        profiles: [ "all", "status", "webserver", "mailserver", "irc", "keepass", "quake" ]
        image: lorcas/docker-telegram-notifier:latest
        platform: ${OS_PLATFORM:-linux/amd64}
        container_name: ${COMPOSE_PROJECT_NAME:+${COMPOSE_PROJECT_NAME}-}notifier
        restart: on-failure:1
        stop_grace_period: 60s
        cpus: "${MICROSERVICE_CPU:-0.25}"
        mem_limit: "${MICROSERVICE_MEMORY:-128m}"
        security_opt:
            - "no-new-privileges:true"
        networks:
            - the-grid
        environment:
            # ℹ️ Notifications only from whitelisted containers: "labels: telegram-notifier.monitor=${TELEGRAM_BOT_SERVICEALERTS_TOKEN:+true}"
            - ONLY_WHITELIST=true
            - TELEGRAM_NOTIFIER_BOT_TOKEN=${TELEGRAM_BOT_SERVICEALERTS_TOKEN:-}
            - TELEGRAM_NOTIFIER_CHAT_ID=${TELEGRAM_BOT_SERVICEALERTS_CHATID:-}
            - ${TELEGRAM_BOT_SERVICEALERTS_CHATTOPICID:+TELEGRAM_NOTIFIER_TOPIC_ID=${TELEGRAM_BOT_SERVICEALERTS_CHATTOPICID}}
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - "${HOST_PATH_TELEGRAM_STATUSMESSAGES_CONFIG:-${HOST_DOCKER_WORKING_DIR}/resources/telegram-notifier/messages.js}:/usr/src/app/templates.js:ro"

    #----------------------------
    # 📊 Docker Services Insights
    #----------------------------
    dashboard:
        profiles: [ "all", "status", "webserver", "mailserver", "irc", "keepass", "quake" ]
        image: portainer/portainer-ce
        platform: ${OS_PLATFORM:-linux/amd64}
        container_name: ${COMPOSE_PROJECT_NAME:+${COMPOSE_PROJECT_NAME}-}dashboard
        restart: on-failure:1
        depends_on:
            - servicealerts
        cpus: "${REVERSEPROXY_CPU:-0.5}"
        mem_limit: "${REVERSEPROXY_MEMORY:-512m}"
        security_opt:
            - "no-new-privileges:true"
        hostname: ${DASHBOARD_HOST:+${DASHBOARD_HOST}.${DOMAINNAME}}
        networks:
            - the-grid
        expose:
            - "9000" # ℹ️ HTTP
            - "9443" # ℹ️ HTTPS (TLS passthrough only)
        labels:
            # -=[ Servicealerting ]=-
            - "telegram-notifier.monitor=${TELEGRAM_BOT_SERVICEALERTS_TOKEN:+true}"
            - "telegram-notifier.service-uri=${DASHBOARD_HOST:+https://${DASHBOARD_HOST}.${DOMAINNAME}}"
            # -=[ traefik Reverse Proxy : routing ON ]=-
            - "traefik.enable=true"
            - "traefik.docker.network=${NETWORK_HTTP_SERVICES:-loadbalance-http}"
            # --- HTTP with SSL/TLS (:9000) ---
            - "traefik.http.routers.${COMPOSE_PROJECT_NAME:+${COMPOSE_PROJECT_NAME}-}portainer-ssl.tls=true"
            - ${USE_LETSENCRYPT:+traefik.http.routers.${COMPOSE_PROJECT_NAME:+${COMPOSE_PROJECT_NAME}-}portainer-ssl.tls.certresolver=letsencrypt}
            - "traefik.http.routers.${COMPOSE_PROJECT_NAME:+${COMPOSE_PROJECT_NAME}-}portainer-ssl.service=${COMPOSE_PROJECT_NAME:+${COMPOSE_PROJECT_NAME}-}portainer-http-service"
            - "traefik.http.routers.${COMPOSE_PROJECT_NAME:+${COMPOSE_PROJECT_NAME}-}portainer-ssl.entryPoints=websecure"
            - "traefik.http.routers.${COMPOSE_PROJECT_NAME:+${COMPOSE_PROJECT_NAME}-}portainer-ssl.rule=Host(`${DASHBOARD_HOST}.${DOMAINNAME}`)"
            - "traefik.http.services.${COMPOSE_PROJECT_NAME:+${COMPOSE_PROJECT_NAME}-}portainer-http-service.loadbalancer.server.port=9000"
        command: >
            --tlscert /certs/live/${DOMAINNAME}/fullchain.cert
            --tlskey /certs/live/${DOMAINNAME}/privkey.key
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - sslcerts-files:/certs/live/${DOMAINNAME}:ro # :ro = read-only
            - portainer-files:/data

    #-----------------------------
    # 🚦 Reverse Proxy and TLS/SSL
    #-----------------------------
    reverseproxy:
        profiles: [ "all", "status", "webserver", "mailserver", "irc" ]
        image: traefik
        platform: ${OS_PLATFORM:-linux/amd64}
        container_name: ${COMPOSE_PROJECT_NAME:+${COMPOSE_PROJECT_NAME}-}reverseproxy
        restart: unless-stopped
        cpus: "${REVERSEPROXY_CPU:-0.5}"
        mem_limit: "${REVERSEPROXY_MEMORY:-512m}"
        security_opt:
            - "no-new-privileges:true"
        networks:
            - the-grid
            - information-superhighway
            - slipgate-teleporter
        ports:
            # -=[ HTTP Services ]=-
            - "${HTTP_PORT:-80}:80/tcp"
            - "${HTTP_PORT_SSL:-443}:443/tcp"
            - "${XDEBUG_PORT:-9003}:9003/tcp"
            # -=[ Mail Server ]=-
            - "${MAILSERVER_PORT_SMTP:-587}:587/tcp"
            - "${MAILSERVER_PORT_SMTP_SSL:-465}:465/tcp"
            # -=[ IRC Server ]=-
            - "${IRC_PORT:-6667}:6667/tcp"
            - "${IRC_PORT_SSL:-6697}:6697/tcp"
            # -=[ SFTP Server ]=-
            - "${KEEPASS_PORT_SFTP:-2222}:2222/tcp"
        expose:
            - "8080"
        labels:
            # -=[ Servicealerting ]=-
            - "telegram-notifier.monitor=${TELEGRAM_BOT_SERVICEALERTS_TOKEN:+true}"
            - ${REVERSEPROXY_DASHBOARD:+telegram-notifier.service-uri=https://${DOMAINNAME}:8080}
            # -=[ traefik Reverse Proxy : routing CONDITIONAL ]=-
            - "traefik.enable=${REVERSEPROXY_DASHBOARD:-false}"
            # --- traefik Dashboard: /dashboard CONDITIONAL ---
            - ${REVERSEPROXY_DASHBOARD:+traefik.http.routers.api.tls=true}
            - ${REVERSEPROXY_DASHBOARD:+${USE_LETSENCRYPT:+traefik.http.routers.api.tls.certresolver=letsencrypt}}
            - ${REVERSEPROXY_DASHBOARD:+traefik.http.routers.api.service=api@internal} # Exposes :8080/tcp
            - ${REVERSEPROXY_DASHBOARD:+traefik.http.routers.api.middlewares=ip-whitelist@file}
            - ${REVERSEPROXY_DASHBOARD:+traefik.http.routers.api.entryPoints=websecure}
            # --- Global redirect to HTTPS ---
            - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
            - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"
            - "traefik.http.routers.${COMPOSE_PROJECT_NAME:+${COMPOSE_PROJECT_NAME}-}http-catchall.rule=HostRegexp(`{host:.+}`)"
            - "traefik.http.routers.${COMPOSE_PROJECT_NAME:+${COMPOSE_PROJECT_NAME}-}http-catchall.entryPoints=web"
            - "traefik.http.routers.${COMPOSE_PROJECT_NAME:+${COMPOSE_PROJECT_NAME}-}http-catchall.middlewares=redirect-to-https"
        command:
            - --global.sendAnonymousUsage=false
            - --api.dashboard=${REVERSEPROXY_DASHBOARD:-false}
            - --api.insecure=${REVERSEPROXY_DASHBOARD:-false}
            - --log.level=${REVERSEPROXY_LOGLEVEL:-ERROR}
            - --providers.docker=true
            - --providers.docker.exposedByDefault=false
            - --providers.file.directory=/config
            - --providers.file.watch=true
            - --serversTransport.insecureSkipVerify=true
            # -=[ WAF Plugin (Coraza) ]=-
            - --experimental.plugins.coraza.modulename=github.com/jcchavezs/coraza-http-wasm-traefik
            - --experimental.plugins.coraza.version=v0.3.0
            # -=[ HTTP Services ]=-
            # --- Default HTTP
            - --entryPoints.web.address=:80
            - --entryPoints.web.http.redirections.entryPoint.to=websecure
            - --entryPoints.web.http.redirections.entryPoint.scheme=https
            - --entryPoints.web.http.redirections.entryPoint.permanent=true
            # --- Default HTTPS
            - --entryPoints.websecure.address=:443
            - --entryPoints.websecure.http.tls=true
            - --entrypoints.websecure.http.maxheaderbytes=5120
            # -=[ Website ]=-
            - --entryPoints.php-xdebug.address=:9003/tcp
            # -=[ Mail Server ]=-
            - --entryPoints.smtp-tcp.address=:587/tcp
            - --entryPoints.smtp-ssl.address=:465/tcp
            # -=[ IRC Server ]=-
            - --entryPoints.irc-tcp.address=:6667/tcp
            - --entryPoints.irc-tcp-ssl.address=:6697/tcp
            # -=[ SFTP Server ]=-
            - --entryPoints.sftp-tcp.address=:2222/tcp
            # -=[ Let's Encrypt configuration ]=-
            - ${USE_LETSENCRYPT:+--certificatesresolvers.letsencrypt.acme.email=${LETSENCRYPT_EMAIL:-hostmaster@${DOMAINNAME}}}
            - ${USE_LETSENCRYPT:+--certificatesresolvers.letsencrypt.acme.storage=/certs/acme.json}
            - ${USE_LETSENCRYPT:+--certificatesresolvers.letsencrypt.acme.tlsChallenge=true}
            - ${USE_LETSENCRYPT:+${LETSENCRYPT_CASERVER:+--certificatesResolvers.letsencrypt.acme.caserver=${LETSENCRYPT_CASERVER}}}
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - sslcerts-files:/certs:rw # :rw = read+write (explicit)
            - "${HOST_PATH_REVERSEPROXY_CONFIG_FILES:-${HOST_DOCKER_WORKING_DIR:-.}/resources/reverseproxy}:/config:ro" # :ro = read-only
            # -=[ Logs ]=-
            - "${HOST_PATH_LOGS:-./logs}/reverseproxy-owasp:/var/lib/coraza"

    #----------------------
    # 🌐 Apache-PHP Website
    #----------------------
    website:
        profiles: [ "all", "webserver" ]
        image: php:${PHP_VERSION:-8.1}-apache
        platform: ${OS_PLATFORM:-linux/amd64}
        container_name: ${COMPOSE_PROJECT_NAME:+${COMPOSE_PROJECT_NAME}-}website
        restart: on-failure:1
        cpus: "${WEBSITE_CPU:-2.0}"
        mem_limit: "${WEBSITE_MEMORY:-2048m}"
        security_opt:
            - "no-new-privileges:true"
        hostname: ${DOMAINNAME}
        networks:
            - the-grid
            - information-superhighway
            - zion-mainframe
        expose:
            - "80"
            - "9003"
        healthcheck:
            test: git --version || exit 1
            start_period: 60s
            interval: 10s
            timeout: 5s
            retries: 10
        labels:
            # -=[ Servicealerting ]=-
            - "telegram-notifier.monitor=${TELEGRAM_BOT_SERVICEALERTS_TOKEN:+true}"
            - "telegram-notifier.service-uri=${DOMAINNAME:+https://${DOMAINNAME}}:${HTTPS_PORT:-443}}"
            # -=[ traefik Reverse Proxy : routing ON ]=-
            - "traefik.enable=true"
            - "traefik.docker.network=${NETWORK_HTTP_SERVICES:-loadbalance-http}"
            # --- Service ports (the container is listening on) ---
            - "traefik.http.routers.${COMPOSE_PROJECT_NAME:+${COMPOSE_PROJECT_NAME}-}main.service=${COMPOSE_PROJECT_NAME:+${COMPOSE_PROJECT_NAME}-}main-service"
            - "traefik.http.services.${COMPOSE_PROJECT_NAME:+${COMPOSE_PROJECT_NAME}-}main-service.loadbalancer.server.port=80"
            - "traefik.http.services.${COMPOSE_PROJECT_NAME:+${COMPOSE_PROJECT_NAME}-}main-service.loadbalancer.passHostHeader=true"
            # --- (DISABLED) Enforce redirect from www. to root-domain (all sites) ---
            # - "traefik.http.middlewares.strip-www.redirectregex.regex=^https?://www.(.+)"
            # - "traefik.http.middlewares.strip-www.redirectregex.replacement=https://$${1}"
            # - "traefik.http.middlewares.strip-www.redirectregex.permanent=true"
            # --- Main website handling ---
            - "traefik.http.routers.${COMPOSE_PROJECT_NAME:+${COMPOSE_PROJECT_NAME}-}main.tls=true"
            - ${USE_LETSENCRYPT:+traefik.http.routers.${COMPOSE_PROJECT_NAME:+${COMPOSE_PROJECT_NAME}-}main.tls.certresolver=letsencrypt}
            - "traefik.http.routers.${COMPOSE_PROJECT_NAME:+${COMPOSE_PROJECT_NAME}-}main.entryPoints=websecure"
            - "traefik.http.routers.${COMPOSE_PROJECT_NAME:+${COMPOSE_PROJECT_NAME}-}main.rule=Host(`${DOMAINNAME:-website}`)"
            - "traefik.http.routers.${COMPOSE_PROJECT_NAME:+${COMPOSE_PROJECT_NAME}-}main.middlewares=owasp-coraza-waf@file,contenttype-add@file,securityheaders-add@file"
            # --- Configure Redirect for Secondary Domainname ---
            - ${SECONDARY_DOMAINNAME:+traefik.http.routers.${COMPOSE_PROJECT_NAME:+${COMPOSE_PROJECT_NAME}-}secondary.tls=true}
            - ${SECONDARY_DOMAINNAME:+${USE_LETSENCRYPT:+traefik.http.routers.${COMPOSE_PROJECT_NAME:+${COMPOSE_PROJECT_NAME}-}secondary.tls.certresolver=letsencrypt}}
            - ${SECONDARY_DOMAINNAME:+traefik.http.routers.${COMPOSE_PROJECT_NAME:+${COMPOSE_PROJECT_NAME}-}secondary.entryPoints=websecure}
            - ${SECONDARY_DOMAINNAME:+traefik.http.routers.${COMPOSE_PROJECT_NAME:+${COMPOSE_PROJECT_NAME}-}secondary.rule=Host(`${SECONDARY_DOMAINNAME}`)}
            - ${SECONDARY_DOMAINNAME:+traefik.http.middlewares.redirect-to-main.redirectregex.regex=^https?://(www\.)?${SECONDARY_DOMAINNAME}/(.*)}
            - ${SECONDARY_DOMAINNAME:+traefik.http.middlewares.redirect-to-main.redirectregex.replacement=https://${DOMAINNAME}/$${2}}
            - ${SECONDARY_DOMAINNAME:+traefik.http.middlewares.redirect-to-main.redirectregex.permanent=true}
            - ${SECONDARY_DOMAINNAME:+traefik.http.routers.${COMPOSE_PROJECT_NAME:+${COMPOSE_PROJECT_NAME}-}secondary.middlewares=redirect-to-main}
            # --- Configure Xdebug (only in DEV mode) - Port 9003 ---
            - ${XDEBUG_PORT:+traefik.tcp.routers.xdebug.entryPoints=php-xdebug}
            - ${XDEBUG_PORT:+traefik.tcp.routers.xdebug.rule=HostSNI(`*`)}
            - ${XDEBUG_PORT:+traefik.tcp.services.xdebug.loadbalancer.server.port=9003}
        environment:
            # 📖 HOWTO https://hub.docker.com/_/php
            TZ: ${TIMEZONE:-Europe/Zurich}
            APACHE_LOG_DIR: /var/log/apache2
            APACHE_PHP_ROOT: ${WEBSITE_ROOT_DIR:-/var/www}
            APACHE_DOCUMENT_ROOT: ${WEBSITE_PUBLIC_DIR:-/var/www/html}
            DEVELOPMENT_MODE: ${WEBSITE_IS_DEVELOPMENT:-}
            INSTALL_APT_GET: ${WEBSITE_APT_GET_INSTALLS:-}
            INSTALL_PHP_EXTENSIONS: ${WEBSITE_PHP_EXTENSIONS:-}
            MAXMIND_ACCOUNT: ${WEBSITE_MAXMIND_GEO2IP_ACCOUNTID:-}
            MAXMIND_LICENSE: ${WEBSITE_MAXMIND_GEO2IP_LICENSEKEY:-}
            GIT_REPO: ${WEBSITE_GIT_REPO:-}
            GIT_BRANCH: ${WEBSITE_GIT_BRANCH:-}
            ${WEBSITE_IS_DEVELOPMENT:+XDEBUG_CONFIG}: >
                client_port=${XDEBUG_PORT:-9003}
                client_host=host.docker.internal
                discover_client_host=true
                idekey=docker
                log=/dev/stdout
                log_level=${XDEBUG_LOGLEVEL:-0}
                mode=${XDEBUG_MODES:-develop,debug}
                start_with_request=yes
                trigger_value=StartProfileForMe
        entrypoint: [ "/bin/bash", "/usr/local/bin/setup.sh" ]
        command: [ "&& sleep 3 && service apache2 restart" ]
        volumes:
            - "${HOST_DOCKER_WORKING_DIR:-.}/resources/website/service-setup.sh:/usr/local/bin/setup.sh"
            # -=[ Logs ]=-
            - "${HOST_PATH_LOGS:-./logs}/website/apache:/var/log/apache2"
            - "${HOST_PATH_LOGS:-./logs}/website/php:/var/log/php" # // ℹ️ Requires change in php.ini to work!
            - "${HOST_PATH_LOGS:-./logs}/website/sendmail:/var/log/msmtp"
            - "${HOST_PATH_LOGS:-./logs}/website/website:${WEBSITE_ROOT_DIR}/logs"
            # -=[ apache2 ]=-
            - "${HOST_DOCKER_WORKING_DIR:-.}/resources/website/apache/maxminddb.conf:/etc/apache2/conf-available/maxminddb.conf:ro" # :ro = read-only
            - "${HOST_PATH_WEBSITE_APACHE_CONFIG:-/dev/null}:/etc/apache2/sites-available/000-default.conf:ro"
            - "${HOST_PATH_WEBSITE_GEO2IP_DBFILE:-/dev/null}:/usr/share/GeoIP/GeoLite2-City/GeoLite2-City.mmdb"
            # -=[ sendmail (msmtp) ]=-
            - "${HOST_PATH_WEBSITE_MSMTP_CONFIG:-/dev/null}:/tmp/msmtprc:ro"
            # -=[ php ]=-
            - "${HOST_PATH_WEBSITE_ENV_FILE:-/dev/null}:/tmp/.env:ro" # :ro = read-only
            # -=[ cron ]=-
            - "${HOST_PATH_WEBSITE_CRONTAB_CONFIG:-/dev/null}:/etc/cron.d/custom"
            - "${HOST_PATH_WEBSITE_CRON_SCRIPTS:-${HOST_DOCKER_WORKING_DIR:-.}/resources/website/cron}:${WEBSITE_ROOT_DIR}/cron"
            # -=[ Website data (user-generated content) ]=-
            - website-files:${WEBSITE_ROOT_DIR}/data:rw # :rw = read+write (explicit)

    #--------------------
    # 💽 MariaDB Database
    #--------------------
    db:
        profiles: [ "all", "webserver" ]
        image: mariadb:${MARIADB_VERSION:-latest}
        platform: ${OS_PLATFORM:-linux/amd64}
        container_name: ${COMPOSE_PROJECT_NAME:+${COMPOSE_PROJECT_NAME}-}mariadb
        restart: on-failure:3
        cpus: "${MARIADB_CPU:-2.0}"
        mem_limit: "${MARIADB_MEMORY:-2560m}"
        security_opt:
            - "no-new-privileges:true"
        networks:
            - zion-mainframe
        expose:
            - "3306/tcp"
        healthcheck:
            test: mariadb ${DATABASE_NAME} --user=${DATABASE_USER} --password='${DATABASE_PASSWORD}' --silent --execute "SELECT 1;"
            start_period: 10s
            interval: 10s
            timeout: 3s
            retries: 5
        labels:
            # -=[ Servicealerting ]=-
            - "telegram-notifier.monitor=${TELEGRAM_BOT_SERVICEALERTS_TOKEN:+true}"
            - "telegram-notifier.service-uri=localhost:${MARIADB_PORT:-3306}}"
            # -=[ traefik Reverse Proxy : routing OFF ]=-
            - "traefik.enable=false"
        environment:
            # 📖 HOWTO https://mariadb.com/kb/en/mariadb-server-docker-official-image-environment-variables/
            - MARIADB_EXTRA_FLAGS=${MARIADB_MYSQLD_OPTIONS:---skip-grant-tables}
            - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=${MARIADB_DISABLE_ROOT_PASSWORD:-no}
            - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD:-}
            - MARIADB_DATABASE=${DATABASE_NAME:-}
            # ℹ️ The following is only required if ≠ "root":
            - MARIADB_ROOT_PASSWORD=${DATABASE_PASSWORD:-${MARIADB_ROOT_PASSWORD}}
            - MARIADB_USER=${DATABASE_USER:-${DATABASE_USER}}
            - MARIADB_PASSWORD=${DATABASE_USER:+${DATABASE_PASSWORD}}
        command: [
            "mariadbd",
            "--log-error=/var/log/mariadb/error.log",
            "--slow-query-log=1",
            "--slow-query-log-file=/var/log/mariadb/slow-query.log",
            "--long-query-time=3",
            "--general-log=${WEBSITE_IS_DEVELOPMENT:+1}",
            "--general-log-file=/var/log/mariadb/queries.log"
            # -- Enable SSL/TLS -- # ℹ️ NOTE Requires PHP to have certs too & use MYSQLI_CLIENT_SSL
            #"--ssl-cert=/certs/fullchain.cert",
            #"--ssl-key=/certs/privkey.key"
        ]
        volumes:
            - sslcerts-files:/certs:ro # :ro = read-only
            - database-files:/var/lib/mysql
            - "${HOST_PATH_LOGS:-./logs}/mariadb:/var/log/mariadb"

    #-------------------
    # 👨‍💻 DB Manager UI
    #-------------------
    db-manager:
        profiles: [ "all", "webserver" ]
        image: wodby/adminer:${DBMANAGER_VERSION:-latest}
        platform: ${OS_PLATFORM:-linux/amd64}
        container_name: ${COMPOSE_PROJECT_NAME:+${COMPOSE_PROJECT_NAME}-}adminer
        restart: on-failure:1
        depends_on:
            - db
        cpus: "${REVERSEPROXY_CPU:-0.5}"
        mem_limit: "${REVERSEPROXY_MEMORY:-512m}"
        #security_opt: # ⚠️ Do NOT limit for adminer to work!
        hostname: ${DBMANAGER_HOST:+${DBMANAGER_HOST}.${DOMAINNAME}}
        networks:
            - zion-mainframe
            - the-grid
        expose:
             - "8080/tcp"
        labels:
            # -=[ Servicealerting ]=-
            - "telegram-notifier.monitor=${TELEGRAM_BOT_SERVICEALERTS_TOKEN:+true}"
            - "telegram-notifier.service-uri=${DBMANAGER_HOST:+https://${DBMANAGER_HOST}.${DOMAINNAME}}"
            # -=[ traefik Reverse Proxy : routing ON ]=-
            - "traefik.enable=true"
            - "traefik.docker.network=${NETWORK_HTTP_SERVICES:-loadbalance-http}"
            # --- HTTP with SSL/TLS (:443) ---
            - "traefik.http.routers.${COMPOSE_PROJECT_NAME:+${COMPOSE_PROJECT_NAME}-}adminer-ssl.tls=true"
            - ${USE_LETSENCRYPT:+traefik.http.routers.${COMPOSE_PROJECT_NAME:+${COMPOSE_PROJECT_NAME}-}adminer-ssl.tls.certresolver=letsencrypt}
            - "traefik.http.routers.${COMPOSE_PROJECT_NAME:+${COMPOSE_PROJECT_NAME}-}adminer-ssl.entrypoints=websecure"
            - "traefik.http.routers.${COMPOSE_PROJECT_NAME:+${COMPOSE_PROJECT_NAME}-}adminer-ssl.rule=Host(`${DBMANAGER_HOST}.${DOMAINNAME}`)"
            - "traefik.http.routers.${COMPOSE_PROJECT_NAME:+${COMPOSE_PROJECT_NAME}-}adminer-ssl.middlewares=ip-whitelist@file,securityheaders-add@file"
        environment:
            # 📖 HOWTO https://github.com/wodby/adminer?tab=readme-ov-file#readme
            - TZ=${TIMEZONE:-Europe/Zurich}
            - ADMINER_DEFAULT_DB_DRIVER=mysql
            - ADMINER_DEFAULT_DB_HOST=${COMPOSE_PROJECT_NAME:+${COMPOSE_PROJECT_NAME}-}mariadb
            - ADMINER_DEFAULT_DB_NAME=${DATABASE_NAME:-}
            - ADMINER_DESIGN=${DBMANAGER_DESIGN:-pappu687}
            - ADMINER_PLUGINS=${DBMANAGER_PLUGINS:-}

    #--------------------------------------------------
    # 📧 Mail Server (outgoing SMTP only, for sendmail)
    #--------------------------------------------------
    postfix-smtp:
        profiles: [ "all", "setup", "mailserver" ]
        image: mailserver/docker-mailserver:latest
        platform: ${OS_PLATFORM:-linux/amd64}
        container_name: ${COMPOSE_PROJECT_NAME:+${COMPOSE_PROJECT_NAME}-}mailserver
        restart: on-failure:3
        cpus: "${MAILSERVER_CPU:-0.5}"
        mem_limit: "${MAILSERVER_MEMORY:-128m}"
        security_opt:
            - "no-new-privileges:true"
        hostname: ${MAILSERVER_HOST:+${MAILSERVER_HOST}.${DOMAINNAME}}
        extra_hosts:
            - "${MAILSERVER_HOST_INTERNAL:-no-mailserver-host-internal-set}.${DOMAINNAME}:127.0.0.1"
        networks:
            - information-superhighway
        expose:
            - "25/tcp" # ℹ️ Unencrypted SMTP for docker-services internally
            - "465/tcp" # ℹ️ SMTP with SSL/TLS
            - "587/tcp" # ℹ️ SMTP with STARTTLS
        healthcheck:
            test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
            start_period: 10s
            timeout: 3s
            retries: 5
        labels:
            # -=[ Servicealerting ]=-
            - "telegram-notifier.monitor=${TELEGRAM_BOT_SERVICEALERTS_TOKEN:+true}"
            - "telegram-notifier.service-uri=${MAILSERVER_HOST:+${MAILSERVER_HOST}.${DOMAINNAME}:${MAILSERVER_PORT_SMTP_SSL:-465}}"
            # -=[ traefik Reverse Proxy : routing ON ]=-
            # 📖 HOWTO See docker-mailserver.github.io/docker-mailserver/v14.0/examples/tutorials/mailserver-behind-proxy/
            - "traefik.enable=true"
            - "traefik.docker.network=${NETWORK_TCP_SERVICES:-loadbalance-tcp}"
            # --- SMTP with STARTTLS (587) ---
            - "traefik.tcp.routers.${COMPOSE_PROJECT_NAME:+${COMPOSE_PROJECT_NAME}-}mailsmtp.tls.passthrough=true"
            - "traefik.tcp.routers.${COMPOSE_PROJECT_NAME:+${COMPOSE_PROJECT_NAME}-}mailsmtp.service=${COMPOSE_PROJECT_NAME:+${COMPOSE_PROJECT_NAME}-}smtp-tcp-service"
            - "traefik.tcp.routers.${COMPOSE_PROJECT_NAME:+${COMPOSE_PROJECT_NAME}-}mailsmtp.entryPoints=smtp-tcp"
            - "traefik.tcp.routers.${COMPOSE_PROJECT_NAME:+${COMPOSE_PROJECT_NAME}-}mailsmtp.rule=HostSNI(`*`)"
            - "traefik.tcp.services.${COMPOSE_PROJECT_NAME:+${COMPOSE_PROJECT_NAME}-}smtp-tcp-service.loadbalancer.server.port=587"
            - ${MAILSERVER_HOST_INTERNAL:+traefik.tcp.routers.${COMPOSE_PROJECT_NAME:+${COMPOSE_PROJECT_NAME}-}internalsmtp.tls.passthrough=true}
            - ${MAILSERVER_HOST_INTERNAL:+traefik.tcp.routers.${COMPOSE_PROJECT_NAME:+${COMPOSE_PROJECT_NAME}-}internalsmtp.entryPoints=smtp-tcp}
            - ${MAILSERVER_HOST_INTERNAL:+traefik.tcp.routers.${COMPOSE_PROJECT_NAME:+${COMPOSE_PROJECT_NAME}-}internalsmtp.rule=HostSNI(`*`)}
            - ${MAILSERVER_HOST_INTERNAL:+traefik.tcp.routers.${COMPOSE_PROJECT_NAME:+${COMPOSE_PROJECT_NAME}-}internalsmtp.service=${COMPOSE_PROJECT_NAME:+${COMPOSE_PROJECT_NAME}-}smtp-tcp-service}
            # --- SMTP with SSL/TLS (465) ---
            - "traefik.tcp.routers.${COMPOSE_PROJECT_NAME:+${COMPOSE_PROJECT_NAME}-}mailsmtp-ssl.tls=true"
            - ${USE_LETSENCRYPT:-traefik.tcp.routers.${COMPOSE_PROJECT_NAME:+${COMPOSE_PROJECT_NAME}-}mailsmtp-ssl.tls.passthrough=true}
            - ${USE_LETSENCRYPT:+traefik.tcp.routers.${COMPOSE_PROJECT_NAME:+${COMPOSE_PROJECT_NAME}-}mailsmtp-ssl.tls.certresolver=letsencrypt}
            - "traefik.tcp.routers.${COMPOSE_PROJECT_NAME:+${COMPOSE_PROJECT_NAME}-}mailsmtp-ssl.service=${COMPOSE_PROJECT_NAME:+${COMPOSE_PROJECT_NAME}-}smtp-ssl-service"
            - "traefik.tcp.routers.${COMPOSE_PROJECT_NAME:+${COMPOSE_PROJECT_NAME}-}mailsmtp-ssl.entryPoints=smtp-ssl"
            - "traefik.tcp.routers.${COMPOSE_PROJECT_NAME:+${COMPOSE_PROJECT_NAME}-}mailsmtp-ssl.rule=HostSNI(`${MAILSERVER_HOST:+${MAILSERVER_HOST}.${DOMAINNAME}}`)"
            - ${USE_LETSENCRYPT:-traefik.tcp.services.${COMPOSE_PROJECT_NAME:+${COMPOSE_PROJECT_NAME}-}smtp-ssl-service.loadbalancer.server.port=465}
            - ${USE_LETSENCRYPT:+traefik.tcp.services.${COMPOSE_PROJECT_NAME:+${COMPOSE_PROJECT_NAME}-}smtp-ssl-service.loadbalancer.server.port=25}
            - ${MAILSERVER_HOST_INTERNAL:+traefik.tcp.routers.${COMPOSE_PROJECT_NAME:+${COMPOSE_PROJECT_NAME}-}internalsmtp-ssl.tls.passthrough=true}
            - ${MAILSERVER_HOST_INTERNAL:+traefik.tcp.routers.${COMPOSE_PROJECT_NAME:+${COMPOSE_PROJECT_NAME}-}internalsmtp-ssl.service=${COMPOSE_PROJECT_NAME:+${COMPOSE_PROJECT_NAME}-}smtp-plain-service}
            - ${MAILSERVER_HOST_INTERNAL:+traefik.tcp.routers.${COMPOSE_PROJECT_NAME:+${COMPOSE_PROJECT_NAME}-}internalsmtp-ssl.entryPoints=smtp-ssl}
            - ${MAILSERVER_HOST_INTERNAL:+${USE_LETSENCRYPT:-traefik.tcp.routers.${COMPOSE_PROJECT_NAME:+${COMPOSE_PROJECT_NAME}-}internalsmtp-ssl.rule=HostSNI(`*`)}}
            - ${MAILSERVER_HOST_INTERNAL:+${USE_LETSENCRYPT:+traefik.tcp.routers.${COMPOSE_PROJECT_NAME:+${COMPOSE_PROJECT_NAME}-}internalsmtp-ssl.rule=HostSNI(`${MAILSERVER_HOST:+${MAILSERVER_HOST}.${DOMAINNAME}}`)}}
            - ${MAILSERVER_HOST_INTERNAL:+traefik.tcp.services.${COMPOSE_PROJECT_NAME:+${COMPOSE_PROJECT_NAME}-}smtp-plain-service.loadbalancer.server.port=25}
        environment:
            # 📖 HOWTO https://docker-mailserver.github.io/docker-mailserver/latest/config/environment/
            - TZ=${TIMEZONE:-Europe/Zurich}
            - PERMIT_DOCKER=connected-networks
            - LOG_LEVEL=${MAILSERVER_LOGLEVEL:-info}
            - POSTMASTER_ADDRESS=postmaster@${DOMAINNAME}
            - ENABLE_POSTFIX_VIRTUAL_TRANSPORT=1
            - POSTFIX_INET_PROTOCOLS=ipv4
            - POSTFIX_MESSAGE_SIZE_LIMIT=${MAILSERVER_EMAIL_MAXSIZE:-10240000}
            - SPOOF_PROTECTION=0
            - SMTP_ONLY=1
            - ENABLE_AMAVIS=0
            - ENABLE_FAIL2BAN=0
            - ENABLE_IMAP=0
            - ENABLE_OPENDKIM=${MAILSERVER_ENABLE_DKIM:-0}
            - ENABLE_OPENDMARC=0
            - ENABLE_POLICYD_SPF=0
            # ℹ️ Supported SSL_TYPE: {empty}->disabled | letsencrypt | manual->specify locations | self-signed
            #- ${USE_LETSENCRYPT:+SSL_TYPE=letsencrypt} # ⛔️ DISABLED because this breaks startup (+ SMTP is anways only internal on the Host)
            - SSL_TYPE=
            - SSL_DOMAIN=${MAILSERVER_HOST:+${MAILSERVER_HOST}.${DOMAINNAME}}
            # (Optional) Relay to external SMTP-provider (Proton, Gmail, etc.)
            - DEFAULT_RELAY_HOST=${SMTP_RELAY_SERVER:-}
            - RELAY_USER=${SMTP_RELAY_USER:-}
            - RELAY_PASSWORD=${SMTP_RELAY_PASSWORD:-}
        volumes:
            #- /etc/localtime:/etc/localtime:ro # Should be obsolete because "TZ" - otherwise: use only on Linux hosts!
            #- sslcerts-files:/etc/letsencrypt:rw # ⛔️ DISABLED (see above)
            - mail-data-files:/var/mail
            - mail-state-files:/var/mail-state
            - "${HOST_PATH_MAILSERVER_CONFIGS:-/dev/null}:/tmp/docker-mailserver"
            - "${HOST_PATH_LOGS:-./logs}/mailserver-smtp:/var/log/mail"

    #--------------
    # 💬 IRC-Server
    #--------------
    irc:
        profiles: [ "all", "irc" ]
        image: c0dy/unrealircd-anope
        platform: linux/amd64 # ℹ️ Has no arm64 support
        container_name: ${COMPOSE_PROJECT_NAME:+${COMPOSE_PROJECT_NAME}-}ircdserver
        restart: on-failure:5
        cpus: "${IRC_CPU:-0.5}"
        mem_limit: "${IRC_MEMORY:-256m}"
        security_opt:
            - "no-new-privileges:true"
        hostname: ${IRC_HOST:+${IRC_HOST}.${DOMAINNAME}}
        networks:
            - information-superhighway
        expose:
            - "6667/tcp" # ℹ️ Unencrypted default IRC Port
            - "6697/tcp" # ℹ️ SSL/TLS encrypted IRC Port
        healthcheck:
            test: |
                ss -ln | grep -q '6667' ||
                exit 1
            start_period: 10s
            interval: 15s
            timeout: 5s
            retries: 5
        labels:
            # -=[ Servicealerting ]=-
            - "telegram-notifier.monitor=${TELEGRAM_BOT_SERVICEALERTS_TOKEN:+true}"
            - "telegram-notifier.service-uri=${IRC_HOST:+irc://${IRC_HOST}.${DOMAINNAME}:${IRC_PORT:-6667}}"
            # -=[ traefik Reverse Proxy : routing ON ]=-
            - "traefik.enable=true"
            - "traefik.docker.network=${NETWORK_TCP_SERVICES:-loadbalance-tcp}"
            # --- IRC (6667/tcp) ---
            - "traefik.tcp.routers.${COMPOSE_PROJECT_NAME:+${COMPOSE_PROJECT_NAME}-}irc.service=${COMPOSE_PROJECT_NAME:+${COMPOSE_PROJECT_NAME}-}irc-tcp-service"
            - "traefik.tcp.routers.${COMPOSE_PROJECT_NAME:+${COMPOSE_PROJECT_NAME}-}irc.entryPoints=irc-tcp"
            - "traefik.tcp.routers.${COMPOSE_PROJECT_NAME:+${COMPOSE_PROJECT_NAME}-}irc.rule=HostSNI(`*`)"
            - "traefik.tcp.services.${COMPOSE_PROJECT_NAME:+${COMPOSE_PROJECT_NAME}-}irc-tcp-service.loadbalancer.server.port=6667"
            # --- IRC with SSL/TLS (6697/tcp) ---
            - "traefik.tcp.routers.${COMPOSE_PROJECT_NAME:+${COMPOSE_PROJECT_NAME}-}irc-ssl.tls=true"
            - ${USE_LETSENCRYPT:-traefik.tcp.routers.${COMPOSE_PROJECT_NAME:+${COMPOSE_PROJECT_NAME}-}irc-ssl.tls.passthrough=true}
            - ${USE_LETSENCRYPT:+traefik.tcp.routers.${COMPOSE_PROJECT_NAME:+${COMPOSE_PROJECT_NAME}-}irc-ssl.tls.certresolver=letsencrypt}
            - "traefik.tcp.routers.${COMPOSE_PROJECT_NAME:+${COMPOSE_PROJECT_NAME}-}irc-ssl.service=${COMPOSE_PROJECT_NAME:+${COMPOSE_PROJECT_NAME}-}irc-ssl-service"
            - "traefik.tcp.routers.${COMPOSE_PROJECT_NAME:+${COMPOSE_PROJECT_NAME}-}irc-ssl.entryPoints=irc-tcp-ssl"
            - ${USE_LETSENCRYPT:-traefik.tcp.routers.${COMPOSE_PROJECT_NAME:+${COMPOSE_PROJECT_NAME}-}irc-ssl.rule=HostSNI(`*`)}
            - ${USE_LETSENCRYPT:+traefik.tcp.routers.${COMPOSE_PROJECT_NAME:+${COMPOSE_PROJECT_NAME}-}irc-ssl.rule=HostSNI(`${IRC_HOST:+${IRC_HOST}.${DOMAINNAME}}`)}
            - ${USE_LETSENCRYPT:-traefik.tcp.services.${COMPOSE_PROJECT_NAME:+${COMPOSE_PROJECT_NAME}-}irc-ssl-service.loadbalancer.server.port=6697}
            - ${USE_LETSENCRYPT:+traefik.tcp.services.${COMPOSE_PROJECT_NAME:+${COMPOSE_PROJECT_NAME}-}irc-ssl-service.loadbalancer.server.port=6667}
        environment:
            - TERM=xterm
            - HOME=/home/ircd
            - TZ=${TIMEZONE:-Europe/Zurich}
        init: true
        tty: true
        entrypoint: ["/bin/bash", "/usr/local/bin/setup.sh"]
        volumes:
            - sslcerts-files:/home/certs:ro # :ro = read-only
            - "${HOST_DOCKER_WORKING_DIR:-.}/resources/irc/service-setup.sh:/usr/local/bin/setup.sh"
            # -=[ Logs ]=-
            #  ⚠️ Requires permission: `sudo chown -R 1000:1000 ./logs/irc-server`
            - "${HOST_PATH_LOGS:-./logs}/irc-server:/var/log:z"
            # -=[ Configs ]=-
            - "${HOST_DOCKER_WORKING_DIR:-.}/resources/irc/anope:/home/ircd/services/conf"
            - "${HOST_DOCKER_WORKING_DIR:-.}/resources/irc/unrealircd:/home/ircd/unrealircd/conf"
            - "${HOST_PATH_IRC_ANOPE_CONFIG_FILES:-/dev/null}:/home/ircd/services/conf/custom:ro"
            - "${HOST_PATH_IRC_IRCD_CONFIG_FILES:-/dev/null}:/home/ircd/unrealircd/conf/custom:ro"
            - "${HOST_PATH_IRC_IRCD_CONFIG_FILES:-/dev/null}/ircd.motd:/home/ircd/unrealircd/conf/ircd.motd:ro"

    #-------------------------
    # 🐍 python Micro-Services
    #-------------------------
    # --- 🧩 Quizbot for IRC ---
    irc-quizbot:
        profiles: [ "all", "irc" ]
        image: python:3.12-slim
        platform: ${OS_PLATFORM:-linux/amd64}
        container_name: ${COMPOSE_PROJECT_NAME:+${COMPOSE_PROJECT_NAME}-}ircquizbot
        restart: on-failure:5
        depends_on:
            irc:
                condition: service_healthy
        cpus: "${MICROSERVICE_CPU:-0.2}"
        mem_limit: "${MICROSERVICE_MEMORY:-128m}"
        security_opt:
            - "no-new-privileges:true"
        networks:
            - information-superhighway
        labels:
            # -=[ Servicealerting ]=-
            - "telegram-notifier.monitor=${TELEGRAM_BOT_SERVICEALERTS_TOKEN:+true}"
            - "telegram-notifier.service-uri=/join #quiz"
            # -=[ traefik Reverse Proxy : routing OFF ]=-
            - "traefik.enable=false"
        environment:
            - TZ=${TIMEZONE:-Europe/Zurich}
            - NICKSERV_PASSWORD=${IRC_QUIZBOT_PASSWORD:-false}
            - BOTMASTERS=${IRC_QUIZBOT_ADMINS:-nickname,barbara}
            - VERBOSE=${IRC_QUIZBOT_DEBUG:-false}
        entrypoint: ["/bin/bash", "/usr/local/bin/setup.sh"]
        volumes:
            - "${HOST_DOCKER_WORKING_DIR:-.}/resources/python/irc-quizbot/service-setup.sh:/usr/local/bin/setup.sh"
            - "${HOST_PATH_IRC_QUIZBOT_CONFIG_FILES:-${HOST_DOCKER_WORKING_DIR:-.}/resources/python/irc-quizbot/configs}:/home/q:ro"

    # --- 📈 Stockticker ---
    stockticker:
        profiles: [ "all" ]
        image: python:3.12-slim
        platform: ${OS_PLATFORM:-linux/amd64}
        container_name: ${COMPOSE_PROJECT_NAME:+${COMPOSE_PROJECT_NAME}-}stockticker
        restart: on-failure:1
        cpus: "${MICROSERVICE_CPU:-0.2}"
        mem_limit: "${MICROSERVICE_MEMORY:-128m}"
        memswap_limit: 512mb
        security_opt:
            - "no-new-privileges:true"
        networks:
            - the-grid
        healthcheck:
            test: '[ ! -f /tmp/unhealthy ]'
            start_period: 60s
            interval: 60s
            timeout: 60s
            retries: 1
        labels:
            # -=[ Servicealerting ]=-
            - "telegram-notifier.monitor=${TELEGRAM_BOT_SERVICEALERTS_TOKEN:+true}"
            - ${STOCKTICKER_SYMBOLS:+telegram-notifier.service-uri=Symbols ${STOCKTICKER_SYMBOLS:-}}
            # -=[ traefik Reverse Proxy : routing OFF ]=-
            - "traefik.enable=false"
        environment:
            - TZ=${TIMEZONE:-Europe/Zurich}
            - STOCK_TICKERS=${STOCKTICKER_SYMBOLS:-}
            - TELEGRAM_TOKEN=${STOCKTICKER_TELEGRAM_BOT_TOKEN:-}
            - TELEGRAM_CHAT=${STOCKTICKER_TELEGRAM_BOT_CHATID:-}
        working_dir: /usr/src/
        entrypoint: ["/bin/bash", "/usr/local/bin/setup.sh"]
        volumes:
            - "${HOST_DOCKER_WORKING_DIR:-.}/resources/python/stockticker/service-setup.sh:/usr/local/bin/setup.sh"
            - "${HOST_DOCKER_WORKING_DIR:-.}/resources/python/stockticker/stock_notifications.py:/usr/src/stock_notifications.py"

    #--------------
    # 🔑 KeePass DB
    #--------------
    sftp:
        profiles: [ "all", "keepass" ]
        image: atmoz/sftp:alpine
        platform: linux/amd64 # ℹ️ Has no arm64 support
        container_name: ${COMPOSE_PROJECT_NAME:+${COMPOSE_PROJECT_NAME}-}keepass
        restart: on-failure:3
        cpus: "${KEEPASS_SFTP_CPU:-0.25}"
        mem_limit: "${KEEPASS_SFTP_MEMORY:-256m}"
        security_opt:
            - "no-new-privileges:true"
        hostname: ${KEEPASS_HOST:+${KEEPASS_HOST}.${DOMAINNAME}}
        networks:
            - information-superhighway
        expose:
            - "22/tcp"
        healthcheck:
            test: |
                nc -z localhost 22 ||
                exit 1
            start_period: 30s
            interval: 15s
            timeout: 5s
            retries: 1
        labels:
            # -=[ Servicealerting ]=-
            - "telegram-notifier.monitor=${TELEGRAM_BOT_SERVICEALERTS_TOKEN:+true}"
            - "telegram-notifier.service-uri=${KEEPASS_HOST:+sftp -P ${KEEPASS_PORT_SFTP:-2222} ${KEEPASS_SFTP_USER}@${KEEPASS_HOST}.${DOMAINNAME}}"
            # -=[ traefik Reverse Proxy : routing ON ]=-
            - "traefik.enable=true"
            - "traefik.docker.network=${NETWORK_TCP_SERVICES:-loadbalance-tcp}"
            # --- SFTP (22/tcp) ---
            - "traefik.tcp.routers.${COMPOSE_PROJECT_NAME:+${COMPOSE_PROJECT_NAME}-}sftp.service=${COMPOSE_PROJECT_NAME:+${COMPOSE_PROJECT_NAME}-}sftp-service"
            - "traefik.tcp.routers.${COMPOSE_PROJECT_NAME:+${COMPOSE_PROJECT_NAME}-}sftp.entryPoints=sftp-tcp"
            - "traefik.tcp.routers.${COMPOSE_PROJECT_NAME:+${COMPOSE_PROJECT_NAME}-}sftp.rule=HostSNI(`*`)"
            - "traefik.tcp.services.${COMPOSE_PROJECT_NAME:+${COMPOSE_PROJECT_NAME}-}sftp-service.loadbalancer.server.port=22"
        command: "${KEEPASS_SFTP_USER:-keepass}:${KEEPASS_SFTP_PASSWORD:-}:::vault"
        volumes:
            - "${HOST_PATH_KEEPASS_SSH_KEYS_DIR:-/etc/ssh}/ssh_host_ed25519_key:/etc/ssh/ssh_host_ed25519_key:ro" # :ro = read-only
            - "${HOST_PATH_KEEPASS_SSH_KEYS_DIR:-/etc/ssh}/ssh_host_rsa_key:/etc/ssh/ssh_host_rsa_key:ro" # :ro = read-only
            - "${HOST_PATH_KEEPASS_DIR:-/dev/null}:/home/${KEEPASS_SFTP_USER:-keepass}"

    #----------------------------
    # 🕹️ Quake 3 Arena Gameserver
    #----------------------------
    # // TODO + Add Stats API: https://hub.docker.com/r/adobromilskiy/quake3-stats
    quake3:
        profiles: [ "all", "quake" ]
        image: jberrenberg/quake3
        platform: linux/amd64 # ℹ️ Has no arm64 support
        container_name: ${COMPOSE_PROJECT_NAME:+${COMPOSE_PROJECT_NAME}-}quake3server
        restart: on-failure:3
        cpus: "${QUAKE3_CPU:-2.0}"
        mem_limit: "${QUAKE3_MEMORY:-2560m}"
        security_opt:
            - "no-new-privileges:true"
        hostname: ${QUAKE3_HOST:+${QUAKE3_HOST}.${DOMAINNAME}}
        networks:
            - slipgate-teleporter
        ports:
            - "${QUAKE3_PORT:-27960}:27960/udp"
        healthcheck:
            test: |
                netstat -nlu | grep 27960 ||
                exit 1
            start_period: 3s
            interval: 5s
            timeout: 10s
            retries: 5
        labels:
            # -=[ Servicealerting ]=-
            - "telegram-notifier.monitor=${TELEGRAM_BOT_SERVICEALERTS_TOKEN:+true}"
            - "telegram-notifier.service-uri=${QUAKE3_HOST:+/connect ${QUAKE3_HOST}.${DOMAINNAME}:${QUAKE3_PORT:-27960}}"
            # -=[ traefik Reverse Proxy : routing OFF ]=-
            # ℹ️ Not using traefik, because: «There must be one (and only one!) UDP service referenced per UDP router!»
            - "traefik.enable=false"
        tty: true
        # ℹ️ NOTE Without explicitely starting a map ("map q3xx") the quake3-Server will not be ready!
        command: "+exec server.cfg ${QUAKE3_RCON_PASSWORD:++rconpassword ${QUAKE3_RCON_PASSWORD}}"
        volumes:
            - "${HOST_PATH_LOGS:-./logs}/quake3-server:/home/ioq3srv/.q3a/baseq3/logs"
            - "${HOST_PATH_QUAKE3_PKG_FILES:-/dev/null}:/home/ioq3srv/ioquake3/baseq3"

    #-----------------
    # 📑 phpDocumentor
    #-----------------
    phpdoc:
        profiles: [ "docu" ]
        image: phpdoc/phpdoc:latest
        platform: ${OS_PLATFORM:-linux/amd64}
        container_name: ${COMPOSE_PROJECT_NAME:+${COMPOSE_PROJECT_NAME}-}phpdocumentor
        restart: "no"
        security_opt:
            - "no-new-privileges:true"
        network_mode: "none"
        environment:
            - GIT_REPO=${WEBSITE_GIT_REPO:-https://github.com/zorgch/zorg-code}
            - GIT_BRANCH=${WEBSITE_GIT_BRANCH:-main}
        command: -c /phpdoc.xml -d /data -t /docs
        volumes:
            - "${HOST_DOCKER_WORKING_DIR:-.}/resources/phpdocumentor/phpdoc.xml:/phpdoc.xml:ro" # :ro = read-only
            - "${HOST_PATH_PHPDOC_SOURCECODE:-/dev/null}:/data"
            - "${HOST_PATH_PHPDOC_OUTPUT:-/dev/null}:/docs"


#==============================
#  --==[ DOCKER NETWORKS ]==--
#==============================
networks:
    zion-mainframe:
        internal: true
        driver: bridge
    the-grid:
        name: ${NETWORK_HTTP_SERVICES:-loadbalance-http}
        external: ${NETWORK_HTTP_SERVICES_SHARED:-false}
        internal: false
    information-superhighway:
        name: ${NETWORK_TCP_SERVICES:-loadbalance-tcp}
        external: ${NETWORK_TCP_SERVICES_SHARED:-false}
        internal: false
    slipgate-teleporter:
        name: ${NETWORK_UDP_SERVICES:-loadbalance-udp}
        external: ${NETWORK_UDP_SERVICES_SHARED:-false}
        internal: false


#================================
# --==[ DOCKER DATA VOLUMES ]==--
#================================
volumes:
    # ℹ️ NOTE "external: false" = managed by Docker in /var/lib/docker/volumes/
    sslcerts-files:
        external: false
    portainer-files:
        external: false
    website-files:
        driver: local
        driver_opts:
            type: none
            device: ${HOST_PATH_WEBSITE_DATA_FILES:-/dev/null}
            o: bind
    database-files:
        external: false
    mail-data-files:
        external: false
    mail-state-files:
        external: false
