#                                                               ██████   ██████   ██████ ██   ██ ███████ ██████
#   ███████  ██████  ████    ██████       ██████  ████   ██     ██   ██ ██    ██ ██      ██  ██  ██      ██   ██
#      ███  ██    ██ ██  ██ ██           ██    ██ ██ ██  ██     ██   ██ ██    ██ ██      █████   █████   ██████
#    ███    ██    ██ ██     ██   ███     ██    ██ ██  ██ ██     ██   ██ ██    ██ ██      ██  ██  ██      ██   ██
#   ███████  ██████  ██      ██████       ██████  ██   ████     ██████   ██████   ██████ ██   ██ ███████ ██   ██
# Portable, Server independent, Docker-based code to get the zorg Websites and Services up, running, and hosted.
# Copyright (C) 2024  zorg Verein <https://github.com/zorgch>
#
#   This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
#
#   This program comes with ABSOLUTELY NO WARRANTY; for details read the README.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see the LICENSE.

#============================
# --==[ DOCKER SERVICES ]==--
#============================
services:
    #----------------------------
    # 🔐 Self-signed certificates
    #----------------------------
    sslcerts:
        profiles: [ "setup" ]
        image: alpine/mkcert
        platform: ${OS_PLATFORM:-linux/arm64}
        container_name: ${COMPOSE_PROJECT_NAME:-docker}-sslcerts
        restart: no
        security_opt:
            - "no-new-privileges:true"
        cap_drop:
            - ALL
        entrypoint: sh
        command: >
            -c 'mkcert -install &&
            mkcert -cert-file /certs/fullchain.cert -key-file /certs/privkey.key ${DOMAINNAME} *.${DOMAINNAME} www.${DOMAINNAME} ${SECONDARY_DOMAINNAME:+${SECONDARY_DOMAINNAME} *.${SECONDARY_DOMAINNAME} www.${SECONDARY_DOMAINNAME}} ${SELFSIGNED_CERT_HOSTS} &&
            cat /root/.local/share/mkcert/rootCA.pem >> /certs/fullchain.cert &&
            chmod 644 /certs/fullchain.cert && chmod 644 /certs/privkey.key'
        volumes:
            - sslcerts-files:/certs:rw # :rw = read+write (explicit)

    #----------------------------
    # 📊 Docker Services Insights
    #----------------------------
    dashboard:
        profiles: [ "all", "status", "webserver", "mailserver", "irc", "quake", "keepass" ]
        image: portainer/portainer-ce
        platform: ${OS_PLATFORM:-linux/arm64}
        container_name: ${COMPOSE_PROJECT_NAME:-docker}-dashboard
        restart: unless-stopped
        depends_on:
            - servicealerts
        cpus: "${REVERSEPROXY_CPU:-0.5}"
        mem_limit: "${REVERSEPROXY_MEMORY:-512m}"
        security_opt:
            - "no-new-privileges:true"
        networks:
            - the-grid
            - information-superhighway
        expose:
            - 9000
            - 9443
        labels:
            - "telegram-notifier.monitor=true"
            - "telegram-notifier.service-uri=${DASHBOARD_HOST:+https://${DASHBOARD_HOST}.${DOMAINNAME}}"
            # Enable reverse-proxy routing
            - "traefik.enable=true"
            - "traefik.http.routers.portainer.tls=true"
            - "traefik.http.routers.portainer.tls.certresolver=${USE_LETSENCRYPT:+letsencrypt}"
            - "traefik.http.routers.portainer.service=portainer-ssl"
            - "traefik.http.routers.portainer.entrypoints=websecure"
            - "traefik.http.routers.portainer.rule=Host(`${DASHBOARD_HOST:+${DASHBOARD_HOST}.${DOMAINNAME}}`)"
            - "traefik.http.services.portainer-ssl.loadbalancer.server.port=9000"
        command: >
            --sslcert /certs/live/${DOMAINNAME:?Error DOMAINNAME is required}/fullchain.cert
            --sslkey /certs/live/${DOMAINNAME:?Error DOMAINNAME is required}/privkey.key
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
            - sslcerts-files:/certs/live/${DOMAINNAME:?Error DOMAINNAME is required}
            - portainer-files:/data

    #-----------------------------
    # 🚦 Reverse Proxy and TLS/SSL
    #-----------------------------
    reverseproxy:
        profiles: [ "all", "status", "webserver", "mailserver" ]
        image: traefik
        platform: ${OS_PLATFORM:-linux/arm64}
        container_name: ${COMPOSE_PROJECT_NAME:-docker}-reverseproxy
        restart: unless-stopped
        cpus: "${REVERSEPROXY_CPU:-0.5}"
        mem_limit: "${REVERSEPROXY_MEMORY:-512m}"
        security_opt:
            - "no-new-privileges:true"
        networks:
            - the-grid
            - information-superhighway
        ports:
            - "${HTTP_PORT:-80}:80"
            - "${HTTP_PORT_SSL:-443}:443"
            - "${MAILSERVER_PORT_SMTP:-587}:587"
            - "${MAILSERVER_PORT_SMTP_SSL:-465}:465"
            - "${XDEBUG_PORT:-9003}:9003"
        labels:
            - "telegram-notifier.monitor=true"
            # Enable
            - "traefik.enable=true"
            # -=[ traefik Plugin: owasp/modsecurity-crs ]=-
            - "traefik.http.middlewares.owaspmodsec.plugin.traefik-modsecurity-plugin.maxbodysize=524288000"
            - "traefik.http.middlewares.owaspmodsec.plugin.traefik-modsecurity-plugin.modsecurityurl=http://reverseproxy-waf:${HTTP_PORT:-80}"
            - "traefik.http.middlewares.owaspmodsec.plugin.traefik-modsecurity-plugin.timeoutmillis=5000"
            - "traefik.http.middlewares.owaspmodsec.plugin.traefik-modsecurity-plugin.failuremode=continue" # Fail "open"
            # -=[ Global redirect to https ]=-
            - "traefik.http.routers.http-catchall.rule=HostRegexp(`{host:.+}`)"
            - "traefik.http.routers.http-catchall.entrypoints=web"
            - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
            - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
            - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"
        command: >
            sh -c '
                traefik \
                --entrypoints.web.address=:${HTTP_PORT:-80} \
                --entrypoints.websecure.address=:${HTTP_PORT_SSL:-443} \
                --entrypoints.php-xdebug.address=:${XDEBUG_PORT:-9003}/tcp \
                --entrypoints.sql-ssl.address=:${MARIADB_PORT:-3306} \
                --entrypoints.smtp-tcp.address=:${MAILSERVER_PORT_SMTP:-587}/tcp \
                --entrypoints.smtp-ssl.address=:${MAILSERVER_PORT_SMTP_SSL:-465} \
                --entrypoints.irc-ssl.address=:${IRC_PORT_SSL:-6697} \
                --entrypoints.keepass-sftp.address=:${KEEPASS_PORT_SFTP:-22}/tcp \
                --entrypoints.quake3-udp.address=:${QUAKE3_PORT:-27960}/udp \
                --entrypoints.web.http.redirections.entrypoint.to=websecure \
                --entrypoints.web.http.redirections.entrypoint.scheme=https \
                --experimental.plugins.traefik-modsecurity-plugin.modulename=github.com/acouvreur/traefik-modsecurity-plugin \
                --experimental.plugins.traefik-modsecurity-plugin.version=v1.3.0 \
                --api.dashboard=false \
                --api.insecure=${REVERSEPROXY_DASHBOARD_UNSECURE:-false} \
                --log.level=${REVERSEPROXY_LOGLEVEL:-ERROR} \
                --providers.docker=true \
                --providers.docker.exposedByDefault=false \
                --serversTransport.insecureSkipVerify=true \
                $(if [ "${USE_LETSENCRYPT}" = "true" ]; then
                    echo "\
                    --certificatesresolvers.letsencrypt.acme.tlschallenge=true \
                    --certificatesresolvers.letsencrypt.acme.storage=/certs/acme.json \
                    --certificatesresolvers.letsencrypt.acme.email=${LETSENCRYPT_EMAIL:?Error LETSENCRYPT_EMAIL is required} \
                    --certificatesresolvers.letsencrypt.acme.caserver=${LETSENCRYPT_CASERVER:-https://acme-v02.api.letsencrypt.org/directory}"
                else
                    echo "\
                    --providers.file.directory=/configuration \
                    --providers.file.watch=true
                    "
                fi)
            '
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
            - sslcerts-files:/certs:rw # :rw = read+write (explicit)
            - "${HOST_DOCKER_WORKING_DIR:-.}/resources/selfsigned-certs.yaml:/configuration/certificates.yaml:ro" # :ro = read-only

    #---------------------
    # 🛡️ OWASP ModSecurity
    #---------------------
    reverseproxy-waf:
        profiles: [ "all", "webserver" ]
        image: owasp/modsecurity-crs:apache-alpine
        platform: ${OS_PLATFORM:-linux/arm64}
        container_name: ${COMPOSE_PROJECT_NAME:-docker}-waf
        restart: unless-stopped
        depends_on:
            - reverseproxy
        cpus: "${WAF_CPU:-0.5}"
        mem_limit: "${WAF_MEMORY:-512m}"
        security_opt:
            - "no-new-privileges:true"
        networks:
            - the-grid
        expose:
            - "${HTTP_PORT:-80}"
        environment:
            # 📖 HOWTO https://github.com/coreruleset/modsecurity-crs-docker?tab=readme-ov-file#common-env-variables
            - LOGLEVEL=WARN
            - TZ=${TIMEZONE:-Europe/Zurich}
            - SERVER_NAME=${DOMAINNAME:-modsec-waf}
            - BACKEND=http://website:${HTTP_PORT:-80}
            - ERRORLOG=/var/log/modsecurity/modsec_error.log
            - APACHE_ALWAYS_TLS_REDIRECT=true
            - PROXY_PRESERVE_HOST=on
            - PROXY_ERROR_OVERRIDE=off
            - SERVER_TOKENS=OS
            # -=[ modsec specific ]=-
            - MODSEC_AUDIT_LOG_FORMAT=JSON
            - MODSEC_UPLOAD_KEEP_FILES=Off
            - MODSEC_AUDIT_LOG=/var/log/modsecurity/modsec_audit.log
            # -=[ CRS specific ]=-
            - ANOMALY_INBOUND=5
            - ANOMALY_OUTBOUND=5
            - BLOCKING_PARANOIA=1
        volumes:
            - "${HOST_PATH_LOGS:-./logs}/reverseproxy-owasp:/var/log/modsecurity"
            - "${HOST_PATH_MODSEC_CRS_REQUEST_RULEFILE:-${HOST_DOCKER_WORKING_DIR}/resources/owasp-modsec/WAF-REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf}:/etc/modsecurity.d/owasp-crs/rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf:ro"
            - "${HOST_PATH_MODSEC_CRS_RESPONSE_RULEFILE:-${HOST_DOCKER_WORKING_DIR}/resources/owasp-modsec/WAF-RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf}:/etc/modsecurity.d/owasp-crs/rules/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf:ro"

    #----------------------
    # 🌐 Apache-PHP Website
    #----------------------
    website:
        profiles: [ "all", "webserver" ]
        image: php:${PHP_VERSION:-8.1}-apache
        platform: ${OS_PLATFORM:-linux/arm64}
        container_name: ${COMPOSE_PROJECT_NAME:-docker}-website
        restart: unless-stopped
        cpus: "${WEBSITE_CPU:-2.0}"
        mem_limit: "${WEBSITE_MEMORY:-2048m}"
        security_opt:
            - "no-new-privileges:true"
        networks:
            - the-grid
        expose:
            - "${HTTP_PORT:-80}"
            - "${XDEBUG_PORT:-9003}"
        healthcheck:
            test: git --version || exit 1
            start_period: 60s
            interval: 10s
            timeout: 5s
            retries: 10
        labels:
            - "telegram-notifier.monitor=true"
            - "telegram-notifier.service-uri=${DOMAINNAME:+https://${DOMAINNAME}}:${HTTPS_PORT:-443}}"
            # Enable reverse-proxy routing
            - "traefik.enable=true"
            # -=[ Service ports (the container is listening on) ]=-
            - "traefik.http.routers.main.service=main-service"
            - "traefik.http.services.main-service.loadbalancer.server.port=${HTTP_PORT:-80}"
            - "traefik.http.services.main-service.loadbalancer.passHostHeader=true"
            # -=[ Enforce redirect from www. to root-domain (all sites) ]=-
            - "traefik.http.middlewares.strip-www.redirectregex.regex=^https?://www.(.+)"
            - "traefik.http.middlewares.strip-www.redirectregex.replacement=https://$${1}"
            - "traefik.http.middlewares.strip-www.redirectregex.permanent=true"
            # -=[ Main website handling ]=-
            - "traefik.http.routers.main.tls=true"
            - "traefik.http.routers.main.tls.certresolver=${USE_LETSENCRYPT:+letsencrypt}"
            - "traefik.http.routers.main.entrypoints=websecure"
            - "traefik.http.routers.main.rule=Host(`${DOMAINNAME:-website}`) || Host(`www.${DOMAINNAME:-website}`)"
            - "traefik.http.routers.main.middlewares=strip-www,owaspmodsec@docker"
            # -=[ Configure Redirect for Secondary Domainname ]=-
            - ${SECONDARY_DOMAINNAME:+traefik.http.routers.secondary.entrypoints=websecure}
            - ${SECONDARY_DOMAINNAME:+traefik.http.routers.secondary.tls=true}
            - ${SECONDARY_DOMAINNAME:+traefik.http.routers.secondary.tls.certresolver=${USE_LETSENCRYPT:+letsencrypt}}
            - ${SECONDARY_DOMAINNAME:+traefik.http.routers.secondary.rule=Host(`${SECONDARY_DOMAINNAME}`) || Host(`www.${SECONDARY_DOMAINNAME}`)}
            - ${SECONDARY_DOMAINNAME:+traefik.http.routers.secondary.middlewares=strip-www,redirect-to-main}
            - ${SECONDARY_DOMAINNAME:+traefik.http.middlewares.redirect-to-main.redirectregex.regex=^https?://(www.)?${SECONDARY_DOMAINNAME}/(.*)}
            - ${SECONDARY_DOMAINNAME:+traefik.http.middlewares.redirect-to-main.redirectregex.replacement=https://${DOMAINNAME}/$${2}}
            - ${SECONDARY_DOMAINNAME:+traefik.http.middlewares.redirect-to-main.redirectregex.permanent=true}
            # -=[ Configure Xdebug (only in DEV mode) ]=-
            - ${WEBSITE_IS_DEVELOPMENT:+traefik.tcp.routers.xdebug.rule=HostSNI(`*`)}
            - ${WEBSITE_IS_DEVELOPMENT:+traefik.tcp.routers.xdebug.entrypoints=php-xdebug}
            - ${WEBSITE_IS_DEVELOPMENT:+traefik.tcp.services.xdebug.loadbalancer.server.port=${XDEBUG_PORT:-9003}}
        environment:
            # 📖 HOWTO https://hub.docker.com/_/php
            TZ: ${TIMEZONE:-Europe/Zurich}
            APACHE_LOG_DIR: /var/log/apache2
            APACHE_PHP_ROOT: ${WESBITE_ROOT_DIR:-/var/www}
            APACHE_DOCUMENT_ROOT: ${WEBSITE_PUBLIC_DIR:-/var/www/html}
            DEVELOPMENT_MODE: ${WEBSITE_IS_DEVELOPMENT:-}
            INSTALL_APT_GET: ${WEBSITE_APT_GET_INSTALLS:-}
            INSTALL_PHP_EXTENSIONS: ${WEBSITE_PHP_EXTENSIONS:-}
            MAXMIND_ACCOUNT: ${WEBSITE_MAXMIND_GEO2IP_ACCOUNTID:-}
            MAXMIND_LICENSE: ${WEBSITE_MAXMIND_GEO2IP_LICENSEKEY:-}
            GIT_REPO: ${WEBSITE_GIT_REPO:?Error a GIT_REPO is required}
            GIT_BRANCH: ${WEBSITE_GIT_BRANCH}
            ${WEBSITE_IS_DEVELOPMENT:+XDEBUG_CONFIG}: >
                client_port=${XDEBUG_PORT:-9003}
                client_host=host.docker.internal
                discover_client_host=true
                idekey=docker
                log=/dev/stdout
                log_level=${XDEBUG_LOGLEVEL:-0}
                mode=${XDEBUG_MODES:-develop,debug}
                start_with_request=yes
                trigger_value=StartProfileForMe
        entrypoint: [ "/bin/bash", "/usr/local/bin/setup.sh" ]
        command: [ "&& sleep 3 && service apache2 restart" ]
        volumes:
            - "${HOST_DOCKER_WORKING_DIR:-.}/resources/website/service-setup.sh:/usr/local/bin/setup.sh"
            # -=[ Logs ]=-
            - "${HOST_PATH_LOGS:-./logs}/website/apache:/var/log/apache2"
            - "${HOST_PATH_LOGS:-./logs}/website/php:/var/log/php" # // ℹ️ Requires change in php.ini to work!
            - "${HOST_PATH_LOGS:-./logs}/website/sendmail:/var/log/msmtp"
            - "${HOST_PATH_LOGS:-./logs}/website/website:${WESBITE_ROOT_DIR}/logs"
            # -=[ apache2 ]=-
            - "${HOST_DOCKER_WORKING_DIR:-.}/resources/website/apache/maxminddb.conf:/etc/apache2/conf-available/maxminddb.conf:ro" # :ro = read-only
            - "${HOST_PATH_WEBSITE_APACHE_CONFIG:?Error an APACHE_CONF is required}:/etc/apache2/sites-available/000-default.conf:ro"
            - "${HOST_PATH_WEBSITE_GEO2IP_DBFILE:+${HOST_PATH_WEBSITE_GEO2IP_DBFILE}:/usr/share/GeoIP/GeoLite2-City/GeoLite2-City.mmdb}"
            # -=[ sendmail (msmtp) ]=-
            - "${HOST_PATH_WEBSITE_MSMTP_CONFIG:?Error MSMTP_CONFIG is required}:/tmp/msmtprc:ro"
            # -=[ php
            - "${HOST_PATH_WEBSITE_ENV_FILE:?Error WEBSITE_ENV_FILE is required}:/tmp/.env:ro" # :ro = read-only
            # -=[ cron ]=-
            - "${HOST_PATH_WEBSITE_CRONTAB_CONFIG:?Error CRONTAB_CONFIG is required}:/etc/cron.d/custom"
            - "${HOST_PATH_WEBSITE_CRON_SCRIPTS:-./resources/website/cron}:${WESBITE_ROOT_DIR}/cron"
            # -=[ Website data (user-generated content) ]=-
            - website-files:${WESBITE_ROOT_DIR}/data:rw # :rw = read+write (explicit)

    #--------------------
    # 💽 MariaDB Database
    #--------------------
    db:
        profiles: [ "all", "webserver" ]
        image: mariadb:${MARIADB_VERSION:-latest}
        platform: ${OS_PLATFORM:-linux/arm64}
        container_name: ${COMPOSE_PROJECT_NAME:-docker}-mariadb
        restart: unless-stopped
        cpus: "${MARIADB_CPU:-2.0}"
        mem_limit: "${MARIADB_MEMORY:-2560m}"
        security_opt:
            - "no-new-privileges:true"
        hostname: ${MARIADB_HOST:+${MARIADB_HOST}.${DOMAINNAME}}
        networks:
            - the-grid
        ports:
            - "${MARIADB_PORT:-3306}:3306"
        healthcheck:
            test: mariadb ${DATABASE_NAME} --user=${DATABASE_USER} --password='${DATABASE_PASSWORD}' --silent --execute "SELECT 1;"
            start_period: 10s
            interval: 10s
            timeout: 3s
            retries: 5
        labels:
            - "telegram-notifier.monitor=true"
            - "telegram-notifier.service-uri=${MARIADB_HOST:+${MARIADB_HOST}.${DOMAINNAME}:${MARIADB_PORT:-3306}}"
        environment:
            # 📖 HOWTO https://mariadb.com/kb/en/mariadb-server-docker-official-image-environment-variables/
            - MARIADB_EXTRA_FLAGS=${MARIADB_MYSQLD_OPTIONS:---skip-grant-tables}
            - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=${MARIADB_DISABLE_ROOT_PASSWORD:-no}
            - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD:-}
            - MARIADB_DATABASE=${DATABASE_NAME:-}
            # The following is only required if ≠ "root":
            - MARIADB_ROOT_PASSWORD=${DATABASE_PASSWORD:-${MARIADB_ROOT_PASSWORD}}
            - MARIADB_USER=${DATABASE_USER:-${DATABASE_USER}}
            - MARIADB_PASSWORD=${DATABASE_USER:+${DATABASE_PASSWORD}}
            # ℹ️ NOTE in some scenarios the following solves Host IP connection issues
            #- MARIADB_ROOT_HOST="%"
        command: [
            "mariadbd",
            "--log-error=/var/log/mariadb/error.log",
            "--slow-query-log=1",
            "--slow-query-log-file=/var/log/mariadb/slow-query.log",
            "--long-query-time=3",
            "--general-log=${WEBSITE_IS_DEVELOPMENT:+1}",
            "--general-log-file=/var/log/mariadb/queries.log"
            # Enable SSL/TLS // ℹ️ NOTE Requires PHP to have certs too & use MYSQLI_CLIENT_SSL
            #"--ssl-cert=/certs/fullchain.cert",
            #"--ssl-key=/certs/privkey.key"
        ]
        volumes:
            - sslcerts-files:/certs
            - database-files:/var/lib/mysql
            - "${HOST_PATH_LOGS:-./logs}/mariadb:/var/log/mariadb"

    #--------------------------------------------------
    # 📧 Mail Server (outgoing SMTP only, for sendmail)
    #--------------------------------------------------
    postfix-smtp:
        profiles: [ "all", "setup", "mailserver" ]
        image: mailserver/docker-mailserver:latest
        platform: ${OS_PLATFORM:-linux/arm64}
        container_name: ${COMPOSE_PROJECT_NAME:-docker}-mailserver
        restart: unless-stopped
        cpus: "${MAILSERVER_CPU:-0.2}"
        mem_limit: "${MAILSERVER_MEMORY:-64m}"
        security_opt:
            - "no-new-privileges:true"
        hostname: ${MAILSERVER_HOST:+${MAILSERVER_HOST}.${DOMAINNAME}}
        networks:
            - the-grid
        expose:
            - "${MAILSERVER_PORT_SMTP_INTERNAL:-25}" # SMTP for docker-services internal (unencrypted & no auth)
            - "${MAILSERVER_PORT_SMTP_SSL:-465}"     # SMTP with SSL/TLS
            - "${MAILSERVER_PORT_SMTP:-587}"         # SMTP with STARTTLS
        healthcheck:
            test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
            start_period: 10s
            timeout: 3s
            retries: 5
        labels:
            - "telegram-notifier.monitor=true"
            - "telegram-notifier.service-uri=${MAILSERVER_HOST:+${MAILSERVER_HOST}.${DOMAINNAME}:${MAILSERVER_PORT_SMTP_SSL:-465}}"
            # 📖 HOWTO See docker-mailserver.github.io/docker-mailserver/v14.0/examples/tutorials/mailserver-behind-proxy/
            - "traefik.enable=true"
            # -=[ SMTP with STARTTLS (587) ]=-
            - "traefik.tcp.routers.mailsmtp.tls=true"
            - "traefik.tcp.routers.mailsmtp.service=smtp-tcp-service"
            - "traefik.tcp.routers.mailsmtp.entrypoints=smtp-tcp"
            - "traefik.tcp.routers.mailsmtp.rule=HostSNI(`*`)"
            - "traefik.tcp.routers.mailsmtp.tls.certresolver=${USE_LETSENCRYPT:+letsencrypt}"
            - "traefik.tcp.services.smtp-tcp-service.loadbalancer.server.port=${MAILSERVER_PORT_SMTP:-587}"
            # -=[ SMTP with SSL/TLS (465) ]=-
            - "traefik.http.routers.mailsmtp-ssl.tls=true"
            - "traefik.http.routers.mailsmtp-ssl.service=smtp-ssl-service"
            - "traefik.http.routers.mailsmtp-ssl.entrypoints=smtp-ssl"
            - "traefik.http.routers.mailsmtp-ssl.rule=Host(`${MAILSERVER_HOST:+${MAILSERVER_HOST}.${DOMAINNAME}}`)"
            - "traefik.http.routers.mailsmtp-ssl.tls.certresolver=${USE_LETSENCRYPT:+letsencrypt}"
            - "traefik.http.services.smtp-ssl-service.loadbalancer.server.port=${MAILSERVER_PORT_SMTP_SSL:-465}"
        environment:
            # 📖 HOWTO https://docker-mailserver.github.io/docker-mailserver/latest/config/environment/
            - TZ=${TIMEZONE:-Europe/Zurich}
            - PERMIT_DOCKER=connected-networks
            - LOG_LEVEL=${MAILSERVER_LOGLEVEL:-info}
            - POSTMASTER_ADDRESS=${MAILSERVER_POSTMASTER:?Error MAILSERVER_POSTMASTER is required}
            - ENABLE_POSTFIX_VIRTUAL_TRANSPORT=1
            - POSTFIX_INET_PROTOCOLS=ipv4
            - POSTFIX_MESSAGE_SIZE_LIMIT=${MAILSERVER_EMAIL_MAXSIZE:-10240000}
            - SPOOF_PROTECTION=0
            - SMTP_ONLY=1
            - ENABLE_AMAVIS=0
            - ENABLE_FAIL2BAN=0
            - ENABLE_IMAP=0
            - ENABLE_OPENDKIM=${MAILSERVER_ENABLE_DKIM:-0}
            - ENABLE_OPENDMARC=0
            - ENABLE_POLICYD_SPF=0
            - SSL_TYPE=${USE_LETSENCRYPT:+letsencrypt} # {empty}->disabled | letsencrypt | manual->specify locations | self-signed
            - SSL_DOMAIN=${MAILSERVER_HOST:+${MAILSERVER_HOST}.${DOMAINNAME}}
            # (Optional) Relay to external SMTP-provider (Proton, Gmail, etc.)
            - DEFAULT_RELAY_HOST=${SMTP_RELAY_SERVER:-}
            - RELAY_USER=${SMTP_RELAY_USER:-}
            - RELAY_PASSWORD=${SMTP_RELAY_PASSWORD:-}
        volumes:
            #- /etc/localtime:/etc/localtime:ro # Should be obsolete because "TZ" - otherwise: use only on Linux hosts!
            - sslcerts-files:/etc/letsencrypt:ro # :ro = read-only
            - mail-data-files:/var/mail
            - mail-state-files:/var/mail-state
            - "${HOST_PATH_LOGS:-./logs}/mailserver-smtp:/var/log/mail"

    #--------------
    # 💬 IRC-Server
    #--------------
    irc:
        profiles: [ "all", "irc" ]
        image: c0dy/unrealircd-anope
        platform: linux/x86_64 # ℹ️ Has no arm64 support
        container_name: ${COMPOSE_PROJECT_NAME:-docker}-ircdserver
        restart: unless-stopped
        cpus: "${IRC_CPU:-0.25}"
        mem_limit: "${IRC_MEMORY:-256m}"
        security_opt:
            - "no-new-privileges:true"
        healthcheck:
            test: |
                ss -ln | grep -q ':${IRC_PORT:-6667}' ||
                exit 1
            start_period: 10s
            interval: 15s
            timeout: 5s
            retries: 5
        hostname: ${IRC_HOST:+${IRC_HOST}.${DOMAINNAME}}
        networks:
            - information-superhighway
        expose:
            - "${IRC_PORT:-6667}:6667"
        ports:
            - "${IRC_PORT_SSL:-6697}:6697"
        labels:
            - "telegram-notifier.monitor=true"
            - "telegram-notifier.service-uri=${IRC_HOST:+irc://${IRC_HOST}.${DOMAINNAME}:${IRC_PORT_SSL:-6697}}"
        environment:
            - TERM=xterm
            - HOME=/home/ircd
            - TZ=${TIMEZONE:-Europe/Zurich}
        init: true
        tty: true
        entrypoint: ["/bin/bash", "/usr/local/bin/setup.sh"]
        volumes:
            - sslcerts-files:/home/certs:ro # :ro = read-only
            - "${HOST_DOCKER_WORKING_DIR:-.}/resources/irc/service-setup.sh:/usr/local/bin/setup.sh"
            - "${HOST_PATH_LOGS:-./logs}/irc-server:/var/log"
            - "${HOST_DOCKER_WORKING_DIR:-.}/resources/irc/anope:/home/ircd/services/conf"
            - "${HOST_DOCKER_WORKING_DIR:-.}/resources/irc/unrealircd:/home/ircd/unrealircd/conf"
            - "${HOST_PATH_IRC_ANOPE_CONFIG_FILES:?Error HOST_PATH_IRC_ANOPE_CONFIG_FILES is required}:/home/ircd/services/conf/custom:ro"
            - "${HOST_PATH_IRC_IRCD_CONFIG_FILES:?Error HOST_PATH_IRC_IRCD_CONFIG_FILES is required}:/home/ircd/unrealircd/conf/custom:ro"
            - "${HOST_PATH_IRC_IRCD_CONFIG_FILES}/ircd.motd:/home/ircd/unrealircd/conf/ircd.motd:ro"

    #-------------------------
    # 🐍 python Micro-Services
    #-------------------------
    # --- 🧩 Quizbot for IRC ---
    irc-quizbot:
        profiles: [ "all", "irc" ]
        image: python:2.7-slim
        platform: linux/x86_64 # ℹ️ Has no arm64 support (py2.7)
        container_name: ${COMPOSE_PROJECT_NAME:-docker}-ircquizbot
        restart: unless-stopped
        depends_on:
            irc:
                condition: service_healthy
        cpus: "${MICROSERVICE_CPU:-0.1}"
        mem_limit: "${MICROSERVICE_MEMORY:-32m}"
        security_opt:
            - "no-new-privileges:true"
        networks:
            - information-superhighway
        labels:
            - "telegram-notifier.monitor=true"
            - "telegram-notifier.service-uri=/join #quiz"
        environment:
            - TZ=${TIMEZONE:-Europe/Zurich}
            - NICKSERV_PASSWORD=${IRC_QUIZBOT_PASSWORD:-false}
        entrypoint: ["/bin/bash", "/usr/local/bin/setup.sh"]
        volumes:
            - "${HOST_DOCKER_WORKING_DIR:-.}/resources/python/irc-quizbot/service-setup.sh:/usr/local/bin/setup.sh"
            - "${HOST_PATH_IRC_QUIZBOT_CONFIG_FILES:-${HOST_DOCKER_WORKING_DIR:-.}/resources/python/irc-quizbot/configs}:/home/q:ro"

    # --- 📈 Stockticker ---
    stockticker:
        profiles: [ "all" ]
        image: python:3.9-slim
        platform: ${OS_PLATFORM:-linux/arm64}
        container_name: ${COMPOSE_PROJECT_NAME:-docker}-stockticker
        restart: unless-stopped
        cpus: "${MICROSERVICE_CPU:-0.1}"
        mem_limit: "${MICROSERVICE_MEMORY:-32m}"
        security_opt:
            - "no-new-privileges:true"
        labels:
            - "telegram-notifier.monitor=true"
        environment:
            - TZ=${TIMEZONE:-Europe/Zurich}
            - STOCK_TICKERS=${STOCKTICKER_SYMBOLS:?Error STOCKTICKER_SYMBOLS is required}
            - TELEGRAM_TOKEN=${TELEGRAM_BOT_TOKEN:?Error TELEGRAM_BOT is required}
            - TELEGRAM_CHAT=${TELEGRAM_BOT_CHATID:?Error TELEGRAM_CHAT is required}
        working_dir: /usr/src/
        entrypoint: ["/bin/bash", "/usr/local/bin/setup.sh"]
        volumes:
            - "${HOST_DOCKER_WORKING_DIR:-.}/resources/python/stockticker/service-setup.sh:/usr/local/bin/setup.sh"
            - "${HOST_DOCKER_WORKING_DIR:-.}/resources/python/stockticker/stock_notifications.py:/usr/src/stock_notifications.py"

    # --- 🚨 Docker Service Notifications ---
    servicealerts:
        profiles: [ "all", "status", "webserver", "mailserver", "irc", "quake", "keepass" ]
        image: lorcas/docker-telegram-notifier:latest
        platform: ${OS_PLATFORM:-linux/arm64}
        container_name: ${COMPOSE_PROJECT_NAME:-docker}-notifier
        restart: unless-stopped
        stop_grace_period: 60s
        cpus: "${MICROSERVICE_CPU:-0.25}"
        mem_limit: "${MICROSERVICE_MEMORY:-128m}"
        security_opt:
            - "no-new-privileges:true"
        environment:
            # ℹ️ Notifications only from whitelisted containers: "labels: telegram-notifier.monitor=true"
            ONLY_WHITELIST: true
            TELEGRAM_NOTIFIER_BOT_TOKEN: ${TELEGRAM_BOT_SERVICEALERTS_TOKEN:-}
            TELEGRAM_NOTIFIER_CHAT_ID: ${TELEGRAM_BOT_SERVICEALERTS_CHATID:-}
            TELEGRAM_NOTIFIER_TOPIC_ID: ${TELEGRAM_BOT_SERVICEALERTS_CHATTOPICID:-}
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
            - "${HOST_PATH_TELEGRAM_STATUSMESSAGES_CONFIG:-${HOST_DOCKER_WORKING_DIR}/resources/telegram-notifier/messages.js}:/usr/src/app/templates.js:ro"

    #--------------
    # 🔑 KeePass DB
    #--------------
    sftp:
        profiles: [ "keepass" ]
        image: atmoz/sftp:alpine
        platform: linux/x86_64 # ℹ️ Has no arm64 support
        container_name: ${COMPOSE_PROJECT_NAME:-docker}-keepass
        restart: unless-stopped
        cpus: "${KEEPASS_SFTP_CPU:-0.1}"
        mem_limit: "${KEEPASS_SFTP_MEMORY:-64m}"
        security_opt:
            - "no-new-privileges:true"
        healthcheck:
            test: |
                nc -z localhost ${KEEPASS_PORT_SFTP:-22} ||
                exit 1
            start_period: 10s
            interval: 15s
            timeout: 5s
            retries: 5
        hostname: ${KEEPASS_HOST:+${KEEPASS_HOST}.${DOMAINNAME}}
        ports:
            - "${KEEPASS_PORT_SFTP:-22}:22"
        labels:
            - "telegram-notifier.monitor=true"
            - "telegram-notifier.service-uri=${KEEPASS_HOST:+sftp://${KEEPASS_HOST}.${DOMAINNAME}:${KEEPASS_PORT_SFTP:-22}}"
        command: "${KEEPASS_SFTP_USER:-keepass}:${KEEPASS_SFTP_PASSWORD:-}:1001"
        volumes:
            - "${HOST_PATH_KEEPASS_FILE:?Error KEEPASS_FILE is required}:/home/${KEEPASS_SFTP_USER:-keepass}/${KEEPASS_KDBX_FILENAME:-database.kdbx}"

    #----------------------------
    # 🕹️ Quake 3 Arena Gameserver
    #----------------------------
    # // TODO + Add Stats API: https://hub.docker.com/r/adobromilskiy/quake3-stats
    quake3:
        profiles: [ "quake" ]
        image: jberrenberg/quake3
        platform: linux/x86_64 # ℹ️ Has no arm64 support
        container_name: ${COMPOSE_PROJECT_NAME:-docker}-quake3server
        restart: no
        cpus: "${QUAKE3_CPU:-2.0}"
        mem_limit: "${QUAKE3_MEMORY:-3072m}"
        security_opt:
            - "no-new-privileges:true"
        healthcheck:
            test: |
                netstat -nlu | grep :${QUAKE3_PORT:-27960} ||
                exit 1
            start_period: 3s
            interval: 5s
            timeout: 10s
            retries: 5
        hostname: ${QUAKE3_HOST:+${QUAKE3_HOST}.${DOMAINNAME}}
        ports:
            - "${QUAKE3_PORT:-27960}:27960/udp"
        labels:
            - "telegram-notifier.monitor=true"
            - "telegram-notifier.service-uri=${QUAKE3_HOST:+quake3://${QUAKE3_HOST}.${DOMAINNAME}:${QUAKE3_PORT:-27960}}"
        tty: true
        command: "+map q3dm6" # ℹ️ NOTE Without using "+map q3xx", the quake3-Server will not be ready!
        volumes:
            - "${HOST_PATH_LOGS:-./logs}/quake3-server:/home/ioq3srv/.q3a/baseq3/logs"
            - "${HOST_PATH_QUAKE3_BASEQ3:?Error HOST_PATH_QUAKE3_BASEQ3 is required}:/home/ioq3srv/.q3a/baseq3"

    #-----------------
    # 📑 phpDocumentor
    #-----------------
    phpdoc:
        profiles: [ "docu" ]
        image: phpdoc/phpdoc:latest
        platform: ${OS_PLATFORM:-linux/arm64}
        container_name: ${COMPOSE_PROJECT_NAME:-docker}-phpdocumentor
        restart: no
        security_opt:
            - "no-new-privileges:true"
        environment:
            - GIT_REPO=${WEBSITE_GIT_REPO:?Error WEBSITE_GIT_REPO is required}
            - GIT_BRANCH=${WEBSITE_GIT_BRANCH:-main}
        command: -d /data -t /docs # FIXME -c /phpdoc.xml | See github.com/phpDocumentor/phpDocumentor/issues/3830
        volumes:
            - "${HOST_DOCKER_WORKING_DIR:-.}/resources/phpdocumentor/phpdoc.xml:/phpdoc.xml:ro" # :ro = read-only
            - "${HOST_PATH_PHPDOC_SOURCECODE:?Error SOURCECODE is required}:/data"
            - "${HOST_PATH_PHPDOC_OUTPUT:?Error PHPDPC_OUTPUT is required}:/docs"


#==============================
#  --==[ DOCKER NETWORKS ]==--
#==============================
networks:
    the-grid:
        driver: bridge
    information-superhighway:
        driver: bridge


#================================
# --==[ DOCKER DATA VOLUMES ]==--
#================================
volumes:
    # "external: false" = Managed by Docker in /var/lib/docker/volumes/
    sslcerts-files:
        external: false
        # // Alternative use locally
        #external: true
        #driver: local
        #driver_opts:
        #    type: none
        #    device: ${HOST_PATH_SSL:?}
        #    o: bind
    portainer-files:
        external: false
    website-files:
        driver: local
        driver_opts:
            type: none
            device: ${HOST_PATH_WEBSITE_DATA_FILES:?}
            o: bind
    database-files:
        external: false
        # // Alternative use locally
        #external: true
        #driver: local
        #driver_opts:
        #    type: none
        #    device: ${HOST_PATH_DATABASE:?}
        #    o: bind
    mail-data-files:
        external: false
    mail-state-files:
        external: false
