# Must match with anope "/sensitive-operators.conf"
oper IamNetadmin {
	/* Required items: */
	class opers;
	mask *@*;
	operclass netadmin; /* The highest level. Includes ability to deop or kill services bots */

	/* Technically you can put oper passwords in plaintext in the conf but
	 * this is HIGHLY DISCOURAGED. Instead you should generate a password hash:
	 * On *NIX, run: ./unrealircd mkpasswd
	 * On Windows, run: "C:\Program Files\UnrealIRCd 6\bin\unrealircdctl" mkpasswd
	 * .. and then paste the result below:
	 */
	password "ChangeMeStrongNetadminPass123"; // NOTE: No more than 32 chars supported
	/* See https://www.unrealircd.org/docs/Authentication_types for
	 * more information, including even better authentication types
	 * such as 'certfp', and how to generate hashes on Windows.
	 */
	/* auto-login no; only used for logins with certfp // Requires UnrealIRCd 6.x */

	/* Auto-join channels when /OPER is successful */
    /* auto-join "#secret"; // FIXME Requires UnrealIRCd 6.x */

	/* Oper permissions are defined in an 'operclass' block.
	 * See https://www.unrealircd.org/docs/Operclass_block
	 * UnrealIRCd ships with a number of default blocks, see
	 * the article for a full list. We choose 'netadmin' here.
	 */
	swhois "is a Network Administrator";
	vhost netadmin.irc.zorg.ch;
	modes "+sqx"; // See https://www.unrealircd.org/docs/User_modes
	/* snomask <snomask>; // See https://www.unrealircd.org/docs/Snomasks */
	/* server-notice-show-event yes; // FIXME Requires UnrealIRCd 6.x */
	/* server-notice-colors yes; // FIXME Requires UnrealIRCd 6.x */
};
oper IamServeradmin {
	/* Required items: */
	class opers;
	mask *@*;
	operclass admin; /* Server administrator similar to globop. But includes ability to use powerful commands such as /SPAMFILTER */

	/* Optional items to further limit who can /OPER */
	password "ChangeMeStrongServadminPass123"; // NOTE: more than 32 chars supported
	/* auto-login no; only used for logins with certfp // Requires UnrealIRCd 6.x */
	/* require-modes <modes>*/
	/* maxlogins <num>;*/

	/* Auto-join channels when /OPER is successful */
	/* auto-join "#secret"; // FIXME Requires UnrealIRCd 6.x */

	/* Optional items to define what will be set upon successful /OPER */
	swhois "is an Administrator";
	vhost netadmin.irc.zorg.ch;
	modes "+sqx"; // See https://www.unrealircd.org/docs/User_modes
	/* snomask <snomask>; // See https://www.unrealircd.org/docs/Snomasks */
	/* server-notice-show-event yes; // FIXME Requires UnrealIRCd 6.x */
	/* server-notice-colors yes; // FIXME Requires UnrealIRCd 6.x */
};
