set {
	network-name 		"Docker zorg IRC";
	default-server 		"irc.zdocker.dev"; /* Must match the me{} block */
//	services-server 	"services.example.org";
//	stats-server 		"stats.example.org";
	help-channel 		"#help";
	hiddenhost-prefix	"Clk";
	prefix-quit 		"Quit";

	/* Cloak keys should be the same at all servers on the network.
	 * They are used for generating masked hosts and should be kept secret.
	 * The keys should be 3 random strings of 50-100 characters
	 * and must consist of lowcase (a-z), upcase (A-Z) and digits (0-9).
	 * HINT: On *NIX, you can run './unrealircd gencloak' in your shell to let
	 *       UnrealIRCd generate 3 random strings for you.
	 */
	cloak-keys {
		"IamThe1stCloackKeyYouNeed2ChangeMe";
		"AndAdditonal2AreNeededHereForIRCD";
		"BecauseIf0GivenItFailsToStartUp2";
	};
};
