/* CHANNEL HISTORY:
 * UnrealIRCd has channel mode +H which can be used by users to read back
 * channel history, such as from before they joined. For general information
 * on this feature, see https://www.unrealircd.org/docs/Channel_history
 *
 * The history limits can be configured via set::history. The defaults are
 * probably already good for you, but if you are on a low-memory system
 * or have thousands of channels then you may want to double check. See
 * https://www.unrealircd.org/docs/Set_block#set::history for the options.
 *
 * In addition to that, you can have "persistent channel history", which
 * means channel history is stored encrypted on disk so it is preserved
 * between IRC server restarts, see
 * https://www.unrealircd.org/docs/Set_block#Persistent_channel_history
 * The persistent history feature is NOT enabled by default because you
 * need to configure a secret { } block for it. The following is a simple
 * example with passwords stored directly in the configuration file.
 * To get better security, read https://www.unrealircd.org/docs/Secret_block
 * on alternative ways so you don't store passwords directly in the config.
 */
# // FIXME This is unrealircd 6.x only :(
# secret historydb { password "Dini3Schwoestere"; };
# set {
#         history {
#                 channel {
#                         persist yes;
#                         db-secret "historydb";

# 						/* How many lines to playback on join? */
#                         playback-on-join {
#                                 lines 15;
#                                 time 1d;
#                         };
#                         /* How much history to keep. These are the
#                          * upper maximums for channel mode +H lines:time
#                          */
#                         max-storage-per-channel {
#                                 /* +r channels have larger maximums: */
#                                 registered {
#                                         lines 10000;
#                                         time 365d;
#                                 };
#                                 /* -r channels have less: */
#                                 unregistered {
#                                         lines 500;
#                                         time 31d;
#                                 };
#                         };
#                 };
#         };
# };
