# Must match with anope "/sensitive-operators.conf"
oper IamNetadmin {
	/* Required items: */
	class opers;
	mask *@*;
	operclass netadmin; /* The highest level. Includes ability to deop or kill services bots */

	/* Technically you can put oper passwords in plaintext in the conf but
	 * this is HIGHLY DISCOURAGED. Instead you should generate a password hash:
	 * On *NIX, run: ./unrealircd mkpasswd
	 * On Windows, run: "C:\Program Files\UnrealIRCd 6\bin\unrealircdctl" mkpasswd
	 * .. and then paste the result below:
	 */
	password "ChangeMeStrongNetadminPass123";
	/* See https://www.unrealircd.org/docs/Authentication_types for
	 * more information, including even better authentication types
	 * such as 'certfp', and how to generate hashes on Windows.
	 */
	/* auto-login no; only used for logins with certfp */

	/* Auto-join channels when /OPER is successful */
    auto-join "#secret";

	/* Oper permissions are defined in an 'operclass' block.
	 * See https://www.unrealircd.org/docs/Operclass_block
	 * UnrealIRCd ships with a number of default blocks, see
	 * the article for a full list. We choose 'netadmin' here.
	 */
	swhois "is a Network Administrator";
	vhost netadmin.irc.zorg.ch;
	modes "+osqx";
	server-notice-show-event yes;
	server-notice-colors yes;
};
oper IamServeradmin {
	/* Required items: */
	class opers;
	mask *@*;
	operclass admin; /* Server administrator similar to globop. But includes ability to use powerful commands such as /SPAMFILTER */

	/* Optional items to further limit who can /OPER */
	password "ChangeMeStrongServadminPass123";
	/* auto-login no; only used for logins with certfp */
	/*require-modes <modes>*/
	/*maxlogins <num>;*/

	/* Auto-join channels when /OPER is successful */
	auto-join "#secret";

	/* Optional items to define what will be set upon successful /OPER */
	swhois "is an Administrator";
	vhost netadmin.irc.zorg.ch;
	modes "+osqx";
	server-notice-show-event yes;
	server-notice-colors yes;
	/* snomask <snomask>; */
};
