# This must be put in anope "sensitive-uplink.conf" so anope can connect to IRCd!
link ircservices.zdocker.dev
{
	incoming {
		# Defines which IP(s) are allowed to connect
		mask 127.0.0.1;
	};
	password "ChangeMeStrongPassForIRCDuplink";
	class servers;
};
/* U-lines give other servers (even) more power/commands.
 * If you use services you must add them here.
 * NEVER put the name of an UnrealIRCd server here!!!
 */
ulines {
	ircservices.zdocker.dev;
};
