ServerName zdocker.dev
ServerAdmin info@zdocker.dev

<VirtualHost *:80>
    DocumentRoot /var/www/html/public/

    # Error Documents
    Alias "/error/" "/var/www/html/public/"
    ErrorDocument 401 /error/error_static.html
    ErrorDocument 403 /error/error_notfound.php
    ErrorDocument 404 /error/error_notfound.php
    ErrorDocument 500 /error/error_static.html

    # Gallery Rewrites
    <IfModule mod_rewrite.c>
        RewriteEngine On
        RewriteRule "^/gallery/thumbs/([0-9]+)$" "/includes/gallery.readpic.php?id=$1&type=tn" [QSA]
        RewriteRule "^/gallery/([0-9]+)$" "/includes/gallery.readpic.php?id=$1" [QSA]
    </IfModule>

    # User Files
    Alias "/files/" "/var/www/data/files/"
    <Directory "/var/www/data/files/">
        Require all granted
    </Directory>
    AliasMatch "^/files/([0-9]+)/(.*)$" "/getfile.php?user=$1&file=$2"

    # User Images
    Alias "/data/userimages/" "/var/www/data/userimages/"
    <Directory "/var/www/data/userimages">
        Require all granted
    </Directory>

    # Tauschbörse Images
    Alias "/images/tauschboerse/" "/var/www/data/tauschboerse/"
    <Directory "/var/www/data/tauschboerse/">
        Require all granted
    </Directory>
</VirtualHost>
