# URL Rewrite: globally ENabled
RewriteEngine On

# Folder file listings & file-name "guessing": globally DISabled
<Directory /var/www/html/>
    Options -Indexes -MultiViews
    AllowOverride All
</Directory>

# Security Headers Einstellungen setzen
<IfModule mod_headers.c>
    Header unset ETag
    Header set X-Frame-Options: "SAMEORIGIN"
    Header set X-XSS-Protection: "1; mode=block"
    Header set X-Content-Type-Options: nosniff
    Header set X-Permitted-Cross-Domain-Policies: "master-only"
</IfModule>

# MaxMind / Geo2Lite-City IP-lookup configs
<IfModule mod_maxminddb.c>
    MaxMindDBEnable On
	<IfFile "/usr/share/GeoIP/GeoLite2-City.mmdb">
		MaxMindDBFile CITY_DB /usr/share/GeoIP/GeoLite2-City.mmdb

		# Assigns lookup results to an environment variable In PHP:
		#    $_SERVER['COUNTRY_CODE'] etc.
		MaxMindDBEnv REGION_CODE  CITY_DB/subdivisions/0/iso_code
		MaxMindDBEnv COUNTRY_CODE CITY_DB/country/iso_code
		MaxMindDBEnv COUNTRY_NAME CITY_DB/country/names/en
		MaxMindDBEnv CITY_NAME CITY_DB/city/names/en
		MaxMindDBEnv LONGITUDE CITY_DB/location/longitude
		MaxMindDBEnv LATITUDE CITY_DB/location/latitude
	</IfFile>
</IfModule>
